//
//  GameScene.swift
//  HomeDesign
//
//  Generated by UntoldEngine Build System
//  visionOS Version
//

import Foundation
import simd
import UntoldEngine

// GameScene: Initialize your game and write game-specific logic
class GameScene {

    var placedFurnitureEntities: [EntityID] = []
    var furnitureModelNames: [EntityID: String] = [:]  // entity → model filename
    var wallItems: [EntityID: SpatialDragPlane] = [:]  // wall entity → drag plane
    var floorplanEntity: EntityID? = nil
    var pendingPlacementEntity: EntityID? = nil
    var pendingModelName: String? = nil              // model name for the in-flight placement
    var selectedEntity: EntityID? = nil
    var undoStack: [UndoAction] = []
    var lastReportedFloorPlanScale: Float = 1.0
    var calibrationComplete: Bool = false
    var calibratedFloorEntityY: Float = 0.0  // entity-space Y of floor plan floor (saved at calibration)
    var savedRealFloorY: Float = 0.0          // ARKit real-world floor Y (saved at calibration)
    var isMiniatureMode: Bool = false
    var ambientLightingEnabled: Bool = true  // matches the initial realWorldLightingContribution set in configureEngineSystems()
    var floorPlanLoadRequested: Bool = false
    var poolPlacement: PoolPlacement? = nil  // set once, from the scene's "pool" marker, if any
    var waterAssetsLoaded: Bool = false
    var waterRippleTimer: Float = 0
    static let waterRippleInterval: Float = 2.5
    var isAnimatingScale: Bool = false
    var scaleAnimTarget: Float = 1.0
    var fullScaleScenePosition: simd_float3 = .zero

    init() {
        Logger.log(message: "🎮 GameScene initializing...")

        // Configure asset paths with debug logging
        logBundleInfo()
        setupAssetPaths()

        // Configure game Systems
        configureEngineSystems()

        // The floor plan loads once the user picks one from the picker UI — see update().
    }

    // MARK: - Setup Methods

    /// Configure game Systems for play mode
    private func configureEngineSystems() {
        gameMode = true
        AnimationSystem.shared.isEnabled = true
        
        registerXREvents()
        setInput(.xr(.pickingBackend(.octreeGPUPreferred)))
        setInput(.xr(.twoHandRotateAxisMode(.dynamicSnapped)))
        
        setRendering(.antiAliasing(.msaa))
        
        // Enables XR probe IBL lighting.
        setRendering(.environment(.lightingMode(.realWorldEstimate)))
        setRendering(.environment(.realWorldLightingContribution(1.0)))
        setPostFX(.ssao(.enabled(false)))
        setRendering(.postProcessing(.disabled))
        
        TextureStreamingSystem.shared.enabled = true
        TextureStreamingSystem.shared.apply(.balanced)

        // Distances appropriate for the scene after its 0.05 scale.
        TextureStreamingSystem.shared.upgradeRadius = 0.15
        TextureStreamingSystem.shared.downgradeRadius = 0.75

        // Conservative visionOS tiers.
        TextureStreamingSystem.shared.maxTextureDimension = 512
        TextureStreamingSystem.shared.minimumTextureDimension = 192

        // Reduce upload spikes.
        TextureStreamingSystem.shared.maxConcurrentOps = 1
        TextureStreamingSystem.shared.updateInterval = 0.3
        
    }

    // MARK: - Game Loop

    /// Called every frame - add custom game logic here
    func update(deltaTime: Float) {
        if gameMode == false { return }

        // Animate the scene scale-in after the user taps to place the floor plan.
        animateScaleIn()

        // No-ops if the loaded floor plan has no pool marker. Refreshed every frame —
        // CoolWater needs the model matrix rewritten continuously even when stationary,
        // or it flickers out (buffered frame uniforms).
        updateWaterMatrix()

        // Keep the water visibly rippling for as long as it's actually shown — the
        // seeded ripples from setupWaterAssets decay to a flat surface after a few
        // seconds otherwise. Independent of the (hidden) sphere entirely.
        if poolPlacement != nil, calibrationComplete, !isMiniatureMode {
            waterRippleTimer += deltaTime
            if waterRippleTimer > Self.waterRippleInterval {
                waterRippleTimer = 0
                spawnAmbientRipple()
            }
        }

        // Track floor plan scale and notify SwiftUI when it changes.
        // Threshold avoids firing Task { @MainActor } every frame at 90 Hz.
        if let fp = floorplanEntity {
            let scale = getScale(entityId: fp).x
            if abs(scale - lastReportedFloorPlanScale) > 0.005 {
                lastReportedFloorPlanScale = scale
                HomeDesignStore.shared.notifyFloorPlanScaleChanged(scale)
            }
        }

        // Load the user's chosen floor plan the first time it's available.
        if !floorPlanLoadRequested, let sceneName = HomeDesignStore.shared.selectedFloorPlanName {
            floorPlanLoadRequested = true
            loadSelectedFloorPlan(named: sceneName)
        }

        // Don't start a new load while an item is awaiting placement confirmation
        if isSceneReady() && pendingPlacementEntity == nil,
           let modelName = FurnitureLoadQueue.shared.dequeue() {
            loadFurnitureItem(modelName: modelName)
        }
    }

    /// Called for input handling - add custom input logic here
    func handleInput() {
        if gameMode == false { return }
        if isSceneReady() == false { return }

        let state = InputSystem.shared.xrSpatialInputState

        // ── Calibration mode ──────────────────────────────────────────────────
        // Wait for the user to tap their real floor before enabling normal input.
        // isAnimatingScale is also guarded so a second tap can't restart placement.
        if !calibrationComplete {
            if state.spatialTapActive, !isAnimatingScale {
                // .horizontalAny + Y-range is more robust than .floorOnly because
                // ARKit sometimes classifies the floor as .unknown early in a session.
                if let floorHit = pickRealSurfacePosition(
                    rayOrigin: state.rayOriginWorld,
                    rayDirection: state.rayDirectionWorld,
                    filter: .horizontalAny,
                    hitYRange: (-0.4)...0.2
                ) {
                    // If the ray also hit the floor plan miniature, convert that
                    // visual-world hit to entity space so we can offset the scene root:
                    // scene_position = floor_hit - entity_room_pos
                    // This places the tapped room at the user's real-world position,
                    // and also automatically compensates for the model's floor Y offset.
                    let roomEntityPos: simd_float3? = {
                        guard let pickedId = state.pickedEntityId,
                              let visualHit = state.pickedEntityWorldPosition,
                              isFloorplanDescendant(pickedId)
                        else { return nil }
                        return SceneRootTransform.shared.visualWorldToSceneLocal(visualHit)
                    }()

                    placeFloorPlanOnFloor(at: floorHit.worldPosition, room: roomEntityPos)
                } else {
                    HomeDesignStore.shared.notifyTransient("No floor detected — point at open floor and tap again")
                }
            }
            return
        }

        if let pending = pendingPlacementEntity {
            // ── Placement mode ───────────────────────────────────────────────
            let srt = SceneRootTransform.shared
            let surface = HomeDesignStore.shared.placementSurface
            let snap = HomeDesignStore.shared.snapEnabled

            if surface == .wall {
                // Wall placement: project ray onto a vertical plane.
                // planeNormal  = horizontal gaze direction (approximates wall face).
                // planePoint   = where ray hits floor plan mesh; fallback 2 m in front.
                let gazeFlat = simd_float3(state.rayDirectionWorld.x, 0, state.rayDirectionWorld.z)
                if simd_length(gazeFlat) > 0.01 {
                    let wallNormal = simd_normalize(gazeFlat)
                    let wallPoint: simd_float3
                    if let hitVisual = state.pickedEntityWorldPosition,
                       let pickedId = state.pickedEntityId,
                       isFloorplanDescendant(pickedId) {
                        wallPoint = hitVisual
                    } else {
                        wallPoint = state.rayOriginWorld + simd_normalize(state.rayDirectionWorld) * 2.0
                    }
                    if let hit = pickPlanePosition(
                        rayOrigin: state.rayOriginWorld,
                        rayDirection: state.rayDirectionWorld,
                        planePoint: wallPoint,
                        planeNormal: wallNormal
                    ) {
                        var entityPos = srt.visualWorldToSceneLocal(hit.worldPosition)
                        if snap { entityPos = snapToGridXY(entityPos) }
                        translateTo(entityId: pending, position: entityPos)
                    }
                }
            } else {
                // Floor placement: project ray onto horizontal plane at the floor plan's surface.
                // visual_floor_Y = scene.position.y + scene.scale.y × calibratedFloorEntityY
                let planeY = srt.position.y + srt.scale.y * calibratedFloorEntityY
                if let hit = pickGroundPosition(
                    rayOrigin: state.rayOriginWorld,
                    rayDirection: state.rayDirectionWorld,
                    planeY: planeY
                ) {
                    var entityPos = srt.visualWorldToSceneLocal(hit.worldPosition)
                    if snap { entityPos = snapToGrid(entityPos) }
                    translateTo(entityId: pending, position: entityPos)
                }
            }

            // Tap confirms placement.
            // For wall items, detect orientation from gaze so the right drag plane is stored.
            if state.spatialTapActive {
                if surface == .wall {
                    let gazeFlat = simd_float3(state.rayDirectionWorld.x, 0, state.rayDirectionWorld.z)
                    let isEastWestFacing = abs(gazeFlat.x) >= abs(gazeFlat.z)
                    let dragPlane: SpatialDragPlane = isEastWestFacing ? .yz : .xy
                    confirmPlacement(pending, wallDragPlane: dragPlane)
                } else {
                    confirmPlacement(pending)
                }
            }

            // Skip normal pinch-drag processing while placing
            return
        }

        // ── Normal mode ──────────────────────────────────────────────────────
        // This demo is a viewer: users pick a floor plan, place it, and look around it.
        // Furniture is never selectable, draggable, rotatable, duplicable, or removable —
        // only floor-plan-level actions (resize, bird's-eye/room navigation) remain.

        // Consume any pending panel action from the UI
        if let action = HomeDesignStore.shared.consumeAction() {
            switch action {
            case .resetFloorPlanScale:
                resetFloorPlanScale()
            case .toggleMiniature:
                toggleMiniatureMode(headPosition: state.rayOriginWorld, gazeDirection: state.rayDirectionWorld)
            case .toggleAmbientLighting:
                toggleAmbientLighting()
            case .remove, .rotateLeft, .rotateRight, .duplicate, .undo:
                break // Furniture manipulation is disabled in this demo.
            }
        }

        if state.spatialTapActive,
           let entityId = state.pickedEntityId,
           isFloorplanDescendant(entityId) {
            if isMiniatureMode {
                // Bird's eye: tap a room to enter it at full scale
                if let visualHit = state.pickedEntityWorldPosition {
                    let entityRoomPos = SceneRootTransform.shared.visualWorldToSceneLocal(visualHit)
                    enterRoom(at: entityRoomPos, headPosition: state.rayOriginWorld)
                }
            } else {
                // Full scale: tap teleports within the floor plan
                if let hitPos = state.pickedEntityWorldPosition {
                    Logger.log(message: "Teleporting to: \(hitPos)")
                    translateSceneBy(delta: simd_float3(-hitPos.x, 0, -hitPos.z))
                }
            }
        }

        // Two-hand resize/rotate applies to the floor plan only, while looking at it.
        if let target = floorplanEntity,
           let picked = state.pickedEntityId,
           isFloorplanDescendant(picked) {
            SpatialManipulationSystem.shared.applyTwoHandZoomIfNeeded(from: state, entityId: target)
            SpatialManipulationSystem.shared.applyTwoHandRotateIfNeeded(from: state, entityId: target)
        }
    }

}

@MainActor
final class EngineStatsWindowStore: ObservableObject {
    static let shared = EngineStatsWindowStore()

    @Published var advancedMode: Bool = false
    @Published private(set) var compactText: String = ""
    @Published private(set) var expandedText: String = ""

    private var timer: Timer?

    private init() {
        refresh()
        timer = Timer.scheduledTimer(withTimeInterval: 0.25, repeats: true) { [weak self] _ in
            guard let self else { return }
            Task { @MainActor in
                self.refresh()
            }
        }
    }

    deinit {
        timer?.invalidate()
    }

    private func refresh() {
        let snapshot = getEngineStatsSnapshot()
        compactText = formatEngineStatsCompact(snapshot)
        expandedText = formatEngineStatsOverlay(snapshot)
    }
}
