//
//  GameSceneUtils.swift
//  HomeDesign
//
//  Generated by UntoldEngine Build System
//  visionOS Version
//

import Foundation
import simd
import UntoldEngine

// Undo actions the app can reverse. Single-level: only the most recent action
// is kept. Drag and scale are not tracked here — the engine anchored-drag
// and two-hand-zoom systems manage their own sessions internally with no
// begin/end hooks exposed to app code. A future engine UndoSystem hook would
// allow tracking those too.
enum UndoAction {
    case placement(entityId: EntityID)
    case snapRotate(entityId: EntityID, previousRotations: simd_float3) // degrees
}

extension GameScene {

    // MARK: - Asset Setup

    /// Log bundle information for debugging
    func logBundleInfo() {
        Logger.log(message: "📦 Bundle path: \(Bundle.main.bundlePath)")
        if let resourceURL = Bundle.main.resourceURL {
            Logger.log(message: "📦 Resource URL: \(resourceURL.path)")
            if let contents = try? FileManager.default.contentsOfDirectory(atPath: resourceURL.path) {
                Logger.log(message: "📦 Resources directory contents: \(contents.joined(separator: ", "))")
            }
        }
    }

    /// Configure the asset base path for the bundled GameData
    func setupAssetPaths() {
        if let gameDataURL = Bundle.main.url(forResource: "GameData", withExtension: nil) {
            assetBasePath = gameDataURL
            Logger.log(message: "✅ Found GameData at: \(gameDataURL.path)")
            if let contents = try? FileManager.default.contentsOfDirectory(atPath: gameDataURL.path) {
                Logger.log(message: "📦 GameData contents: \(contents.joined(separator: ", "))")
            }
        } else if let resourceURL = Bundle.main.resourceURL {
            let gameDataPath = resourceURL.appendingPathComponent("GameData")
            if FileManager.default.fileExists(atPath: gameDataPath.path) {
                assetBasePath = gameDataPath
                Logger.log(message: "✅ Found GameData in Resources: \(gameDataPath.path)")
                if let contents = try? FileManager.default.contentsOfDirectory(atPath: gameDataPath.path) {
                    Logger.log(message: "📦 GameData contents: \(contents.joined(separator: ", "))")
                }
            } else {
                Logger.log(message: "⚠️ GameData not found. Bundle resources: \(resourceURL.path)")
                Logger.log(message: "⚠️ Listing all files in bundle resources...")
                listDirectoryRecursively(at: resourceURL)
            }
        } else {
            Logger.log(message: "❌ Bundle.main.resourceURL is nil!")
        }
    }

    // MARK: - Calibration

    /// Anchor the scene and start the scale-in animation.
    ///
    /// - Parameters:
    ///   - floorHit: Real-world floor position from ARKit (visual-world space).
    ///   - room: Entity-space position of the tapped point on the floor plan miniature.
    ///
    /// When `room` is provided the scene root is offset so that entity point appears
    /// at `floorHit` at full scale:
    ///   scene_position = floorHit - room
    ///
    /// This achieves two things at once:
    ///   1. The chosen room ends up at the user's real-world location when scaled up.
    ///   2. The model's floor geometry Y (which may not be 0) is automatically
    ///      compensated — room.y is the model's actual floor surface height.
    ///
    /// Without `room` the scene origin (entity 0,0,0) is placed at `floorHit`.
    func placeFloorPlanOnFloor(at floorHit: simd_float3, room: simd_float3? = nil) {
        let scenePosition: simd_float3
        // Always save the real ARKit floor Y — used when re-entering from bird's eye.
        savedRealFloorY = floorHit.y

        if let room {
            scenePosition = floorHit - room
            calibratedFloorEntityY = room.y
            Logger.log(message: "📍 Floor hit: \(floorHit) | Room entity pos: \(room) | calibratedFloorEntityY=\(room.y) | Scene origin → \(scenePosition)")
        } else {
            scenePosition = floorHit
            calibratedFloorEntityY = 0.0
            Logger.log(message: "📍 Floor hit: \(floorHit) — no floor plan hit, placing at origin")
        }
        translateSceneTo(position: scenePosition)
        scaleAnimTarget = 1.0
        isAnimatingScale = true
    }

    /// Smoothly lerp the scene scale toward `scaleAnimTarget` each frame.
    /// Handles both calibration scale-in (0.05 → 1.0) and miniature toggle.
    /// Called every frame from update() while isAnimatingScale is true.
    func animateScaleIn() {
        guard isAnimatingScale else { return }
        let current = SceneRootTransform.shared.scale.x
        let target = scaleAnimTarget
        let next = current + (target - current) * 0.08  // ease-out lerp at ~90 Hz
        if abs(next - target) < 0.005 {
            scaleSceneTo(target)
            isAnimatingScale = false
            if !calibrationComplete {
                calibrationComplete = true
                HomeDesignStore.shared.notifyCalibrationComplete()
                Logger.log(message: "✅ Calibration complete")
            }
            HomeDesignStore.shared.notifyMiniatureModeChanged(isMiniatureMode)
        } else {
            scaleSceneTo(next)
        }
    }

    /// Toggle between miniature (bird's-eye) and full-scale view.
    ///
    /// `SceneRootTransform.scale` is animated; no entity transforms are modified.
    ///
    /// When going miniature, the scene root is repositioned so the floor plan
    /// appears at the user's current feet (headPosition X/Z, calibration floor Y).
    /// Without this, the miniature would cluster around the original scene root
    /// which can be several metres away from where the user is standing.
    /// The full-scale position is saved and restored on the way back.
    func toggleMiniatureMode(headPosition: simd_float3, gazeDirection: simd_float3) {
        guard calibrationComplete, !isAnimatingScale else { return }
        isMiniatureMode.toggle()
        if isMiniatureMode {
            fullScaleScenePosition = SceneRootTransform.shared.position
            let floorY = fullScaleScenePosition.y

            // Project the gaze direction onto the horizontal plane, normalize it,
            // then offset the miniature 0.7 m in front of the user so it's in
            // their field of view rather than directly below their feet.
            let gazeFlat = simd_float3(gazeDirection.x, 0, gazeDirection.z)
            let gazeFlatLen = simd_length(gazeFlat)
            let forwardOffset: Float = 0.7
            let miniaturePos: simd_float3
            if gazeFlatLen > 0.01 {
                let forward = gazeFlat / gazeFlatLen
                miniaturePos = simd_float3(
                    headPosition.x + forward.x * forwardOffset,
                    floorY,
                    headPosition.z + forward.z * forwardOffset
                )
            } else {
                miniaturePos = simd_float3(headPosition.x, floorY, headPosition.z)
            }

            translateSceneTo(position: miniaturePos)
            scaleAnimTarget = 0.05
            Logger.log(message: "🔍 Miniature → placed at \(miniaturePos)")
        } else {
            translateSceneTo(position: fullScaleScenePosition)
            scaleAnimTarget = 1.0
            Logger.log(message: "🔍 Full scale → restoring position \(fullScaleScenePosition)")
        }
        isAnimatingScale = true
    }

    /// Enter the tapped room from bird's eye view.
    ///
    /// Computes a new scene root so the chosen entity-space point lands at the
    /// user's current real-world feet, then animates scale from 0.05 → 1.0.
    ///
    ///   scenePos.x = headPos.x − room.x   (room aligns to user's lateral position)
    ///   scenePos.y = savedRealFloorY − room.y  (real ARKit floor height compensates for model offset)
    ///   scenePos.z = headPos.z − room.z
    ///
    /// Also updates fullScaleScenePosition so the "Full Scale" button escape
    /// restores to this newly entered room on subsequent toggles.
    func enterRoom(at entityRoomPos: simd_float3, headPosition: simd_float3) {
        guard isMiniatureMode, !isAnimatingScale else { return }

        let newScenePos = simd_float3(
            headPosition.x - entityRoomPos.x,
            savedRealFloorY - entityRoomPos.y,
            headPosition.z - entityRoomPos.z
        )

        fullScaleScenePosition = newScenePos
        translateSceneTo(position: newScenePos)
        isMiniatureMode = false
        scaleAnimTarget = 1.0
        isAnimatingScale = true

        Logger.log(message: "🚪 Entering room at entity \(entityRoomPos) → scene origin \(newScenePos)")
    }

    // MARK: - Floorplan Helpers

    /// Returns true if `entityId` is the floorplan root or any of its descendants.
    /// Used to distinguish a tap on the floor plan from a tap on furniture.
    func isFloorplanDescendant(_ entityId: EntityID) -> Bool {
        guard let root = floorplanEntity else { return false }
        var current: EntityID? = entityId
        while let id = current {
            if id == root { return true }
            current = getEntityParent(entityId: id)
        }
        return false
    }

    // MARK: - Furniture Loading

    /// Load a furniture model, apply the ghost preview material, and enter placement mode.
    func loadFurnitureItem(modelName: String) {
        setSceneReady(false)

        let entity = createEntity()
        setEntityName(entityId: entity, name: modelName)

        setEntityMeshAsync(entityId: entity, filename: modelName, withExtension: "untold") { [weak self] success in
            if success {
                rotateTo(entityId: entity, angle: 0.0, axis: simd_float3(0.0, 1.0, 0.0))
                self?.applyMaterial(to: entity, opacity: 0.5, emissive: .zero)
                self?.pendingPlacementEntity = entity
                // Store the model name here, AFTER the async load, because the engine
                // overwrites setEntityName during parsing (e.g. "bed_01_01" → "bed_01_01.root").
                // pendingModelName is consumed by confirmPlacement and written into furnitureModelNames.
                self?.pendingModelName = modelName
                Logger.log(message: "🪑 \(modelName) loaded — look at the floor and tap to place")
            } else {
                Logger.log(message: "❌ Failed to load mesh: \(modelName)")
            }
            setSceneReady(success)
        }
    }

    /// Record the model name, commit the entity, and auto-select it.
    /// Pass `wallDragPlane` for wall-mounted items so the correct drag plane
    /// (.xy or .yz) is stored for future drag gestures.
    func confirmPlacement(_ entityId: EntityID,
                          wallDragPlane: SpatialDragPlane? = nil) {
        placedFurnitureEntities.append(entityId)
        furnitureModelNames[entityId] = pendingModelName
        pendingModelName = nil
        pendingPlacementEntity = nil
        if let plane = wallDragPlane {
            wallItems[entityId] = plane
        }
        pushUndo(.placement(entityId: entityId))
        selectEntity(entityId)
        let surfaceTag = wallDragPlane.map { "wall (\($0))" } ?? "floor"
        Logger.log(message: "✅ Furniture placed on \(surfaceTag)")
    }

    // MARK: - Selection

    /// Select a placed furniture entity: highlight it and notify SwiftUI.
    func selectEntity(_ entityId: EntityID) {
        if let prev = selectedEntity { applyMaterial(to: prev, opacity: 1.0, emissive: .zero) }
        selectedEntity = entityId
        applyMaterial(to: entityId, opacity: 1.0, emissive: simd_float3(0.8, 0.6, 0.0))
        HomeDesignStore.shared.notifySelectionChanged(hasSelection: true)
    }

    /// Clear the current selection, removing the highlight.
    func deselectEntity() {
        if let entity = selectedEntity { applyMaterial(to: entity, opacity: 1.0, emissive: .zero) }
        selectedEntity = nil
        HomeDesignStore.shared.notifySelectionChanged(hasSelection: false)
    }

    /// Destroy the selected entity and remove it from the placed list.
    func removeSelectedEntity() {
        guard let entity = selectedEntity else { return }
        destroyEntity(entityId: entity)
        placedFurnitureEntities.removeAll { $0 == entity }
        furnitureModelNames.removeValue(forKey: entity)
        wallItems.removeValue(forKey: entity)
        selectedEntity = nil
        HomeDesignStore.shared.notifySelectionChanged(hasSelection: false)
        Logger.log(message: "🗑 Entity removed")
    }

    // MARK: - Undo

    /// Push an action onto the single-slot undo stack, replacing any prior entry.
    func pushUndo(_ action: UndoAction) {
        undoStack = [action]
        HomeDesignStore.shared.notifyUndoStateChanged(canUndo: true)
    }

    func performUndo() {
        guard let action = undoStack.popLast() else { return }

        switch action {
        case .placement(let entityId):
            if selectedEntity == entityId {
                selectedEntity = nil
                HomeDesignStore.shared.notifySelectionChanged(hasSelection: false)
            }
            destroyEntity(entityId: entityId)
            placedFurnitureEntities.removeAll { $0 == entityId }
            furnitureModelNames.removeValue(forKey: entityId)
            wallItems.removeValue(forKey: entityId)
            Logger.log(message: "↩ Undo: removed placed item")

        case .snapRotate(let entityId, let previousRotations):
            applyAxisRotations(entityId: entityId, axis: previousRotations)
            Logger.log(message: "↩ Undo: restored rotation")
        }

        HomeDesignStore.shared.notifyUndoStateChanged(canUndo: !undoStack.isEmpty)
    }

    // MARK: - Duplicate

    /// Queue another copy of the selected item into placement mode.
    /// Uses furnitureModelNames (not getEntityName) because the engine overwrites
    /// the entity name with an internal value during async mesh loading.
    func duplicateSelectedEntity() {
        guard let entity = selectedEntity,
              let modelName = furnitureModelNames[entity]
        else { return }
        FurnitureLoadQueue.shared.enqueue(modelName)
        Logger.log(message: "📋 Duplicating: \(modelName)")
    }

    // MARK: - Floor Plan Scale

    /// Reset the floor plan to its original (1×) scale.
    func resetFloorPlanScale() {
        guard let fp = floorplanEntity else { return }
        scaleTo(entityId: fp, scale: simd_float3(1, 1, 1))
        HomeDesignStore.shared.notifyFloorPlanScaleChanged(1.0)
        Logger.log(message: "↺ Floor plan scale reset")
    }

    // MARK: - Rotation

    /// Snap-rotate the selected entity by the given degrees around the Y axis.
    /// Captures the previous rotation so the action can be undone.
    func rotateSelectedEntityBy(degrees: Float) {
        guard let entity = selectedEntity else { return }
        let current = getAxisRotations(entityId: entity)
        pushUndo(.snapRotate(entityId: entity, previousRotations: current))
        applyAxisRotations(entityId: entity, axis: simd_float3(current.x, current.y + degrees, current.z))
    }

    /// Walk up the scenegraph to find which placed furniture root (if any)
    /// the picked entity belongs to. Handles multi-mesh hierarchical models.
    func placedFurnitureRoot(for entityId: EntityID) -> EntityID? {
        var current: EntityID? = entityId
        while let id = current {
            if placedFurnitureEntities.contains(id) { return id }
            current = getEntityParent(entityId: id)
        }
        return nil
    }

    // MARK: - Material Helpers

    /// Apply opacity and emissive to an entity and its entire descendant hierarchy.
    func applyMaterial(to entityId: EntityID, opacity: Float, emissive: simd_float3) {
        updateMaterialOpacity(entityId: entityId, opacity: opacity, recursive: true)
        updateMaterialEmmisive(entityId: entityId, emmissive: emissive, recursive: true)
    }

    /// Recursively list directory contents for debugging
    func listDirectoryRecursively(at url: URL, depth: Int = 0) {
        let indent = String(repeating: "  ", count: depth)
        guard let contents = try? FileManager.default.contentsOfDirectory(atPath: url.path) else {
            return
        }
        for item in contents {
            let itemURL = url.appendingPathComponent(item)
            var isDirectory: ObjCBool = false
            if FileManager.default.fileExists(atPath: itemURL.path, isDirectory: &isDirectory) {
                Logger.log(message: "\(indent)📁 \(item)\(isDirectory.boolValue ? "/" : "")")
                if isDirectory.boolValue && depth < 2 {
                    listDirectoryRecursively(at: itemURL, depth: depth + 1)
                }
            }
        }
    }

}
