//
//  GameSceneUtils.swift
//  HomeDesign
//
//  Generated by UntoldEngine Build System
//  visionOS Version
//

import Foundation
import simd
import Metal
import UntoldEngine
import CoolWater

// Undo actions the app can reverse. Single-level: only the most recent action
// is kept. Drag and scale are not tracked here — the engine anchored-drag
// and two-hand-zoom systems manage their own sessions internally with no
// begin/end hooks exposed to app code. A future engine UndoSystem hook would
// allow tracking those too.
enum UndoAction {
    case placement(entityId: EntityID)
    case snapRotate(entityId: EntityID, previousRotations: simd_float3) // degrees
}

extension GameScene {

    // MARK: - Asset Setup

    /// Log bundle information for debugging
    func logBundleInfo() {
        Logger.log(message: "📦 Bundle path: \(Bundle.main.bundlePath)")
        if let resourceURL = Bundle.main.resourceURL {
            Logger.log(message: "📦 Resource URL: \(resourceURL.path)")
            if let contents = try? FileManager.default.contentsOfDirectory(atPath: resourceURL.path) {
                Logger.log(message: "📦 Resources directory contents: \(contents.joined(separator: ", "))")
            }
        }
    }

    /// Configure the asset base path for the bundled GameData
    func setupAssetPaths() {
        if let gameDataURL = Bundle.main.url(forResource: "GameData", withExtension: nil) {
            assetBasePath = gameDataURL
            Logger.log(message: "✅ Found GameData at: \(gameDataURL.path)")
            if let contents = try? FileManager.default.contentsOfDirectory(atPath: gameDataURL.path) {
                Logger.log(message: "📦 GameData contents: \(contents.joined(separator: ", "))")
            }
        } else if let resourceURL = Bundle.main.resourceURL {
            let gameDataPath = resourceURL.appendingPathComponent("GameData")
            if FileManager.default.fileExists(atPath: gameDataPath.path) {
                assetBasePath = gameDataPath
                Logger.log(message: "✅ Found GameData in Resources: \(gameDataPath.path)")
                if let contents = try? FileManager.default.contentsOfDirectory(atPath: gameDataPath.path) {
                    Logger.log(message: "📦 GameData contents: \(contents.joined(separator: ", "))")
                }
            } else {
                Logger.log(message: "⚠️ GameData not found. Bundle resources: \(resourceURL.path)")
                Logger.log(message: "⚠️ Listing all files in bundle resources...")
                listDirectoryRecursively(at: resourceURL)
            }
        } else {
            Logger.log(message: "❌ Bundle.main.resourceURL is nil!")
        }
    }

    // MARK: - Floor Plan Loading

    /// Load the user's chosen pre-furnished floor plan and register its contents:
    /// the room shell becomes `floorplanEntity`; any entity whose model matches a
    /// known catalog item becomes selectable/movable furniture, exactly like an
    /// item placed from the catalog — just without the placement-flow side effects
    /// (no ghost material, no undo entry, no auto-select).
    func loadSelectedFloorPlan(named sceneName: String) {
        let modelBaseNames = SceneManifest.modelBaseNames(sceneName: sceneName)
        let priorEntities = Set(getAllGameEntities())
        let totalToLoad = modelBaseNames?.count ?? 0

        // `AssetLoadingState` is the engine's own per-entity mesh-load tracker — every
        // `setEntityMeshAsync` call (including the ones `loadUntoldScene` makes internally
        // for each entity) brackets itself with start/finishLoading. `loadingCount()` is
        // engine-wide, not scoped to this scene, but nothing else loads concurrently during
        // this window (the furniture catalog is gated behind `isSceneReady()`, which stays
        // false until this load finishes), so `total - loadingCount()` is a reliable count
        // of how many of *this* scene's models have finished.
        var progressTask: Task<Void, Never>?
        if totalToLoad > 0 {
            HomeDesignStore.shared.notifyFloorPlanLoadProgress(LoadProgress(completed: 0, total: totalToLoad))
            progressTask = Task {
                while !Task.isCancelled {
                    try? await Task.sleep(for: .milliseconds(100))
                    guard !Task.isCancelled else { return }
                    let stillLoading = await AssetLoadingState.shared.loadingCount()
                    let completed = min(totalToLoad, max(0, totalToLoad - stillLoading))
                    HomeDesignStore.shared.notifyFloorPlanLoadProgress(LoadProgress(completed: completed, total: totalToLoad))
                }
            }
        }

        loadUntoldScene(named: sceneName) { [weak self] success in
            guard let self else { return }
            progressTask?.cancel()
            HomeDesignStore.shared.notifyFloorPlanLoadProgress(nil)
            guard success else {
                Logger.log(message: "❌ Failed to load floor plan scene: \(sceneName)")
                HomeDesignStore.shared.notifyTransient("Couldn't load floor plan")
                return
            }
            self.registerLoadedFloorPlan(modelBaseNames: modelBaseNames, priorEntities: priorEntities)
            // Start at miniature scale so the user can place it on their real floor.
            scaleSceneTo(0.05)
            setSceneReady(true)
        }
    }

    /// Sorts the entities spawned by `loadUntoldScene` into the room shell
    /// (`floorplanEntity`) and pre-placed furniture (registered like placed items).
    ///
    /// Live entities can't be queried for their asset after loading (see
    /// `SceneManifest`), so identification instead correlates by creation order:
    /// `deserializeScene` calls `createEntity()` for every *authored* top-level entity
    /// synchronously, in file order, before any async mesh loading (which may spawn
    /// additional derived child entities later, always at higher IDs) completes. So the
    /// lowest N new entity IDs — N = the manifest's entity count — are exactly the
    /// authored entities, in the same order as `modelBaseNames`.
    private func registerLoadedFloorPlan(modelBaseNames: [String?]?, priorEntities: Set<EntityID>) {
        guard let modelBaseNames else {
            Logger.log(message: "⚠️ Could not read floor plan scene manifest — nothing will be selectable")
            return
        }

        let knownModels = Set(FurnitureCatalog.knownModelNames())

        let newEntities = getAllGameEntities()
            .filter { !priorEntities.contains($0) }
            .sorted()

        guard newEntities.count >= modelBaseNames.count else {
            Logger.log(message: "⚠️ Floor plan scene spawned fewer entities (\(newEntities.count)) than authored (\(modelBaseNames.count)) — registration may be incomplete")
            return
        }

        let authoredEntities = newEntities.prefix(modelBaseNames.count)

        for (entityId, modelName) in zip(authoredEntities, modelBaseNames) {
            guard let modelName else { continue } // camera, light, empty group — not interactive
            if knownModels.contains(modelName) {
                registerPreplacedFurniture(entityId: entityId, modelName: modelName)
            } else {
                floorplanEntity = entityId
            }
        }

        if let floorplanEntity {
            // Quick test: the room shell never moves relative to itself once loaded
            // (only the whole scene root rigidly translates/scales during calibration),
            // so it's a safe static-batching candidate — unlike furniture, which needs
            // independent per-entity transforms for select/drag/rotate.
            setEntityStaticBatchHierarchy(entityId: floorplanEntity)
            setBatching(.enabled(true))
            generateBatches()

            // The pool marker isn't necessarily a top-level authored entity — in an
            // imported multi-part asset (e.g. a SketchUp villa), it can be a named node
            // deep inside the asset's own hierarchy, only reachable by name once the
            // asset instance's overrides have applied (which has happened by now, since
            // loadUntoldScene's completion only fires after all async loads finish).
            let poolCandidates = getAllGameEntities().filter {
                $0 != floorplanEntity
                    && isFloorplanDescendant($0)
                    && getEntityName(entityId: $0).lowercased().contains(poolMarkerModelName)
            }
            if let poolEntityId = poolCandidates.first {
                registerPoolMarker(entityId: poolEntityId)
            } else {
                // Never leave the extension at its default identity transform. That
                // would render a 2x2 demo pool at the scene origin when marker lookup
                // fails, obscuring the actual problem.
                setCoolWaterModelMatrix(Self.hiddenWaterMatrix)
                Logger.log(message: "⚠️ No pool marker found in the floor-plan hierarchy")
            }
        } else {
            Logger.log(message: "⚠️ No room-shell entity found in floor plan scene — calibration will not work")
        }
    }

    /// Register a furniture entity that came pre-placed in a loaded floor plan scene.
    /// Wall vs. floor and drag plane are inferred from its authored transform since,
    /// unlike interactive placement, there's no live gaze direction to read.
    func registerPreplacedFurniture(entityId: EntityID, modelName: String) {
        placedFurnitureEntities.append(entityId)
        furnitureModelNames[entityId] = modelName

        let position = getLocalPosition(entityId: entityId)
        let rotation = getAxisRotations(entityId: entityId)
        if case .wall(let dragPlane) = classifySurface(entityY: position.y, yRotationDegrees: rotation.y) {
            wallItems[entityId] = dragPlane
        }
    }

    // MARK: - Calibration

    /// Anchor the scene and start the scale-in animation.
    ///
    /// - Parameters:
    ///   - floorHit: Real-world floor position from ARKit (visual-world space).
    ///   - room: Entity-space position of the tapped point on the floor plan miniature.
    ///
    /// When `room` is provided the scene root is offset so that entity point appears
    /// at `floorHit` at full scale:
    ///   scene_position = floorHit - room
    ///
    /// This achieves two things at once:
    ///   1. The chosen room ends up at the user's real-world location when scaled up.
    ///   2. The model's floor geometry Y (which may not be 0) is automatically
    ///      compensated — room.y is the model's actual floor surface height.
    ///
    /// Without `room` the scene origin (entity 0,0,0) is placed at `floorHit`.
    func placeFloorPlanOnFloor(at floorHit: simd_float3, room: simd_float3? = nil) {
        let scenePosition: simd_float3
        // Always save the real ARKit floor Y — used when re-entering from bird's eye.
        savedRealFloorY = floorHit.y

        if let room {
            scenePosition = floorHit - room
            calibratedFloorEntityY = room.y
            Logger.log(message: "📍 Floor hit: \(floorHit) | Room entity pos: \(room) | calibratedFloorEntityY=\(room.y) | Scene origin → \(scenePosition)")
        } else {
            scenePosition = floorHit
            calibratedFloorEntityY = 0.0
            Logger.log(message: "📍 Floor hit: \(floorHit) — no floor plan hit, placing at origin")
        }
        translateSceneTo(position: scenePosition)
        scaleAnimTarget = 1.0
        isAnimatingScale = true
    }

    /// Smoothly lerp the scene scale toward `scaleAnimTarget` each frame.
    /// Handles both calibration scale-in (0.05 → 1.0) and miniature toggle.
    /// Called every frame from update() while isAnimatingScale is true.
    func animateScaleIn() {
        guard isAnimatingScale else { return }
        let current = SceneRootTransform.shared.scale.x
        let target = scaleAnimTarget
        let next = current + (target - current) * 0.08  // ease-out lerp at ~90 Hz
        if abs(next - target) < 0.005 {
            scaleSceneTo(target)
            isAnimatingScale = false
            if !calibrationComplete {
                calibrationComplete = true
                HomeDesignStore.shared.notifyCalibrationComplete()
                Logger.log(message: "✅ Calibration complete")
            }
            HomeDesignStore.shared.notifyMiniatureModeChanged(isMiniatureMode)
        } else {
            scaleSceneTo(next)
        }
    }

    /// Toggle between miniature (bird's-eye) and full-scale view.
    ///
    /// `SceneRootTransform.scale` is animated; no entity transforms are modified.
    ///
    /// When going miniature, the scene root is repositioned so the floor plan
    /// appears at the user's current feet (headPosition X/Z, calibration floor Y).
    /// Without this, the miniature would cluster around the original scene root
    /// which can be several metres away from where the user is standing.
    /// The full-scale position is saved and restored on the way back.
    func toggleMiniatureMode(headPosition: simd_float3, gazeDirection: simd_float3) {
        guard calibrationComplete, !isAnimatingScale else { return }
        isMiniatureMode.toggle()
        if isMiniatureMode {
            fullScaleScenePosition = SceneRootTransform.shared.position
            let floorY = fullScaleScenePosition.y

            // Project the gaze direction onto the horizontal plane, normalize it,
            // then offset the miniature 0.7 m in front of the user so it's in
            // their field of view rather than directly below their feet.
            let gazeFlat = simd_float3(gazeDirection.x, 0, gazeDirection.z)
            let gazeFlatLen = simd_length(gazeFlat)
            let forwardOffset: Float = 0.7
            let miniaturePos: simd_float3
            if gazeFlatLen > 0.01 {
                let forward = gazeFlat / gazeFlatLen
                miniaturePos = simd_float3(
                    headPosition.x + forward.x * forwardOffset,
                    floorY,
                    headPosition.z + forward.z * forwardOffset
                )
            } else {
                miniaturePos = simd_float3(headPosition.x, floorY, headPosition.z)
            }

            translateSceneTo(position: miniaturePos)
            scaleAnimTarget = 0.05
            Logger.log(message: "🔍 Miniature → placed at \(miniaturePos)")
        } else {
            translateSceneTo(position: fullScaleScenePosition)
            scaleAnimTarget = 1.0
            Logger.log(message: "🔍 Full scale → restoring position \(fullScaleScenePosition)")
        }
        isAnimatingScale = true
    }

    /// Enter the tapped room from bird's eye view.
    ///
    /// Computes a new scene root so the chosen entity-space point lands at the
    /// user's current real-world feet, then animates scale from 0.05 → 1.0.
    ///
    ///   scenePos.x = headPos.x − room.x   (room aligns to user's lateral position)
    ///   scenePos.y = savedRealFloorY − room.y  (real ARKit floor height compensates for model offset)
    ///   scenePos.z = headPos.z − room.z
    ///
    /// Also updates fullScaleScenePosition so the "Full Scale" button escape
    /// restores to this newly entered room on subsequent toggles.
    func enterRoom(at entityRoomPos: simd_float3, headPosition: simd_float3) {
        guard isMiniatureMode, !isAnimatingScale else { return }

        let newScenePos = simd_float3(
            headPosition.x - entityRoomPos.x,
            savedRealFloorY - entityRoomPos.y,
            headPosition.z - entityRoomPos.z
        )

        fullScaleScenePosition = newScenePos
        translateSceneTo(position: newScenePos)
        isMiniatureMode = false
        scaleAnimTarget = 1.0
        isAnimatingScale = true

        Logger.log(message: "🚪 Entering room at entity \(entityRoomPos) → scene origin \(newScenePos)")
    }

    // MARK: - Floorplan Helpers

    /// Returns true if `entityId` is the floorplan root or any of its descendants.
    /// Used to distinguish a tap on the floor plan from a tap on furniture.
    func isFloorplanDescendant(_ entityId: EntityID) -> Bool {
        guard let root = floorplanEntity else { return false }
        var current: EntityID? = entityId
        while let id = current {
            if id == root { return true }
            current = getEntityParent(entityId: id)
        }
        return false
    }

    // MARK: - Furniture Loading

    /// Load a furniture model, apply the ghost preview material, and enter placement mode.
    func loadFurnitureItem(modelName: String) {
        setSceneReady(false)

        let entity = createEntity()
        setEntityName(entityId: entity, name: modelName)

        setEntityMeshAsync(entityId: entity, filename: modelName, withExtension: "untold") { [weak self] success in
            if success {
                rotateTo(entityId: entity, angle: 0.0, axis: simd_float3(0.0, 1.0, 0.0))
                self?.applyMaterial(to: entity, opacity: 0.5, emissive: .zero)
                self?.pendingPlacementEntity = entity
                // Store the model name here, AFTER the async load, because the engine
                // overwrites setEntityName during parsing (e.g. "bed_01_01" → "bed_01_01.root").
                // pendingModelName is consumed by confirmPlacement and written into furnitureModelNames.
                self?.pendingModelName = modelName
                Logger.log(message: "🪑 \(modelName) loaded — look at the floor and tap to place")
            } else {
                Logger.log(message: "❌ Failed to load mesh: \(modelName)")
                HomeDesignStore.shared.notifyTransient("Couldn't load \(modelName)")
            }
            setSceneReady(success)
        }
    }

    /// Record the model name, commit the entity, and auto-select it.
    /// Pass `wallDragPlane` for wall-mounted items so the correct drag plane
    /// (.xy or .yz) is stored for future drag gestures.
    func confirmPlacement(_ entityId: EntityID,
                          wallDragPlane: SpatialDragPlane? = nil) {
        placedFurnitureEntities.append(entityId)
        furnitureModelNames[entityId] = pendingModelName
        pendingModelName = nil
        pendingPlacementEntity = nil
        if let plane = wallDragPlane {
            wallItems[entityId] = plane
        }
        pushUndo(.placement(entityId: entityId))
        selectEntity(entityId)
        let surfaceTag = wallDragPlane.map { "wall (\($0))" } ?? "floor"
        Logger.log(message: "✅ Furniture placed on \(surfaceTag)")
    }

    // MARK: - Selection

    /// Select a placed furniture entity: highlight it and notify SwiftUI.
    func selectEntity(_ entityId: EntityID) {
        if let prev = selectedEntity { applyMaterial(to: prev, opacity: 1.0, emissive: .zero) }
        selectedEntity = entityId
        applyMaterial(to: entityId, opacity: 1.0, emissive: simd_float3(0.8, 0.6, 0.0))
        HomeDesignStore.shared.notifySelectionChanged(hasSelection: true)
    }

    /// Clear the current selection, removing the highlight.
    func deselectEntity() {
        if let entity = selectedEntity { applyMaterial(to: entity, opacity: 1.0, emissive: .zero) }
        selectedEntity = nil
        HomeDesignStore.shared.notifySelectionChanged(hasSelection: false)
    }

    /// Destroy the selected entity and remove it from the placed list.
    func removeSelectedEntity() {
        guard let entity = selectedEntity else { return }
        destroyEntity(entityId: entity)
        placedFurnitureEntities.removeAll { $0 == entity }
        furnitureModelNames.removeValue(forKey: entity)
        wallItems.removeValue(forKey: entity)
        selectedEntity = nil
        HomeDesignStore.shared.notifySelectionChanged(hasSelection: false)
        Logger.log(message: "🗑 Entity removed")
    }

    // MARK: - Undo

    /// Push an action onto the single-slot undo stack, replacing any prior entry.
    func pushUndo(_ action: UndoAction) {
        undoStack = [action]
        HomeDesignStore.shared.notifyUndoStateChanged(canUndo: true)
    }

    func performUndo() {
        guard let action = undoStack.popLast() else { return }

        switch action {
        case .placement(let entityId):
            if selectedEntity == entityId {
                selectedEntity = nil
                HomeDesignStore.shared.notifySelectionChanged(hasSelection: false)
            }
            destroyEntity(entityId: entityId)
            placedFurnitureEntities.removeAll { $0 == entityId }
            furnitureModelNames.removeValue(forKey: entityId)
            wallItems.removeValue(forKey: entityId)
            Logger.log(message: "↩ Undo: removed placed item")

        case .snapRotate(let entityId, let previousRotations):
            applyAxisRotations(entityId: entityId, axis: previousRotations)
            Logger.log(message: "↩ Undo: restored rotation")
        }

        HomeDesignStore.shared.notifyUndoStateChanged(canUndo: !undoStack.isEmpty)
    }

    // MARK: - Duplicate

    /// Queue another copy of the selected item into placement mode.
    /// Uses furnitureModelNames (not getEntityName) because the engine overwrites
    /// the entity name with an internal value during async mesh loading.
    func duplicateSelectedEntity() {
        guard let entity = selectedEntity,
              let modelName = furnitureModelNames[entity]
        else { return }
        FurnitureLoadQueue.shared.enqueue(modelName)
        Logger.log(message: "📋 Duplicating: \(modelName)")
    }

    // MARK: - Floor Plan Scale

    /// Reset the floor plan to its original (1×) scale.
    func resetFloorPlanScale() {
        guard let fp = floorplanEntity else { return }
        scaleTo(entityId: fp, scale: simd_float3(1, 1, 1))
        HomeDesignStore.shared.notifyFloorPlanScaleChanged(1.0)
        Logger.log(message: "↺ Floor plan scale reset")
    }

    // MARK: - Lighting

    /// Toggle the real-world (ARKit passthrough) lighting contribution between fully off
    /// and fully on, so users can compare the scene under pure scripted lighting vs. lit
    /// by their actual room.
    func toggleAmbientLighting() {
        ambientLightingEnabled.toggle()
        setRendering(.environment(.realWorldLightingContribution(ambientLightingEnabled ? 1.0 : 0.0)))
        HomeDesignStore.shared.notifyAmbientLightingChanged(ambientLightingEnabled)
        Logger.log(message: "💡 Ambient lighting: \(ambientLightingEnabled ? "on" : "off")")
    }

    // MARK: - Water

    /// Capture the pool marker's transform, then remove it — it's a
    /// pure positioning proxy for CoolWater's pool and is never itself rendered (it's
    /// already authored with opacity 0). Loads the pool's art as soon as it's found;
    /// visibility/position are handled separately, every frame, by `updateWaterMatrix`
    /// (the pool may still be hidden behind calibration/miniature-mode gating at this
    /// point).
    ///
    func registerPoolMarker(entityId: EntityID) {
        guard let markerWorld = scene.get(component: WorldTransformComponent.self, for: entityId)?.space else {
            Logger.log(message: "⚠️ Pool marker has no world transform")
            return
        }

        // Store the marker relative to the floor-plan root. This retains every nested
        // parent translation and rotation while allowing the floor plan's live scale to
        // continue affecting the water after the marker entity has been removed.
        let floorplanWorld = floorplanEntity.flatMap {
            scene.get(component: WorldTransformComponent.self, for: $0)?.space
        } ?? matrix_identity_float4x4
        let inverseFloorplanWorld = simd_inverse(floorplanWorld)
        var relativeTransform = simd_mul(inverseFloorplanWorld, markerWorld)

        // Imported SketchUp parts have identity node translations and bake their real
        // placement into mesh vertices. Transform the mesh center through the marker's
        // complete hierarchy so the water lands on the visible pool rather than at the
        // asset root.
        if let local = scene.get(component: LocalTransformComponent.self, for: entityId) {
            let localCenter = (local.boundingBox.min + local.boundingBox.max) / 2
            let worldCenter = markerWorld * simd_float4(localCenter, 1)
            let floorplanCenter = inverseFloorplanWorld * worldCenter
            relativeTransform.columns.3 = simd_float4(
                floorplanCenter.x,
                floorplanCenter.y,
                floorplanCenter.z,
                1
            )
        }

        // The marker's scale describes its proxy mesh, not the water. Strip it while
        // retaining the marker origin and orientation; CoolWater uses an explicit scale.
        func normalizedAxis(_ column: simd_float4) -> simd_float4 {
            let axis = simd_float3(column.x, column.y, column.z)
            let length = simd_length(axis)
            return length > 0.0001 ? column / length : column
        }
        relativeTransform.columns.0 = normalizedAxis(relativeTransform.columns.0)
        relativeTransform.columns.1 = normalizedAxis(relativeTransform.columns.1)
        relativeTransform.columns.2 = normalizedAxis(relativeTransform.columns.2)

        poolPlacement = PoolPlacement(relativeTransform: relativeTransform)
        destroyEntity(entityId: entityId)
        let origin = simd_float3(relativeTransform.columns.3.x,
                                 relativeTransform.columns.3.y,
                                 relativeTransform.columns.3.z)
        Logger.log(message: "🏊 Pool marker origin: \(origin), water scale: \(Self.waterScale)")
        setupWaterAssets()
    }

    /// CoolWater's authored pool spans -1...1 on X/Z, so its model scale is half
    /// the desired 8.74 x 16.6 metre footprint. Y must remain non-zero because the
    /// renderer inverts this matrix for camera rays and real-world occlusion.
    private static let waterScale = simd_float3(8.74 / 2, 0.6, 16.6 / 2)

    /// Loads the pool's art and seeds the simulation. Runs once.
    private func setupWaterAssets() {
        guard !waterAssetsLoaded else { return }
        waterAssetsLoaded = true

        guard let device = MTLCreateSystemDefaultDevice() else {
            Logger.log(message: "❌ Water: no Metal device")
            return
        }
        if let tiles = WaterAssets.loadTexture(device: device, name: "tiles", ext: "jpg", srgb: true, mipmapped: true) {
            setCoolWaterTilesTexture(tiles)
        }
        if let sky = WaterAssets.loadCubemap(device: device) {
            setCoolWaterSkyTexture(sky)
        }
        setCoolWaterLightDirection(simd_float3(2.0, 2.0, -1.0))
        seedCoolWaterRipples(count: 8)
        Logger.log(message: "💧 Water assets loaded")
    }

    /// Injects one subtle ripple at a random point in the pool's local space so the
    /// water stays visibly alive — the ripples seeded in `setupWaterAssets` decay to a
    /// flat surface after a few seconds otherwise. Called on a timer from `update()`,
    /// entirely independent of the (hidden) sphere.
    func spawnAmbientRipple() {
        let x = Float.random(in: -0.8 ... 0.8)
        let z = Float.random(in: -0.8 ... 0.8)
        addCoolWaterDrop(center: simd_float2(x, z), radius: 0.03, strength: Bool.random() ? 0.01 : -0.01)
        Logger.log(message: "💧 Ambient ripple at (\(x), \(z))")
    }

    /// Pushes the pool's scene-local model matrix every frame — CoolWater needs it refreshed
    /// continuously even when stationary, or it flickers out (buffered frame uniforms).
    /// Hidden (degenerate matrix, parked well below the floor) until calibration
    /// completes and while in miniature/bird's-eye mode, matching how furniture
    /// interaction and floor-plan resize are already scoped in `handleInput()`.
    /// No-ops entirely if the loaded floor plan has no pool marker.
    ///
    /// The stored marker transform is relative to `floorplanEntity`. Composing it with
    /// the floor plan's current world transform preserves the complete hierarchy,
    /// including future translation, rotation, and scale changes.
    func updateWaterMatrix() {
        guard let pool = poolPlacement else { return }

        guard calibrationComplete, !isMiniatureMode else {
            setCoolWaterModelMatrix(Self.hiddenWaterMatrix)
            return
        }

        let floorplanWorld = floorplanEntity.flatMap {
            scene.get(component: WorldTransformComponent.self, for: $0)?.space
        } ?? matrix_identity_float4x4
        // RenderPassContext.camera already contains SceneRootTransform through the
        // engine's effective view matrix. Keep this model in entity/scene-local space;
        // multiplying the scene root here would apply teleport/scale twice.
        let model = floorplanWorld * pool.relativeTransform
            * simd_float4x4(waterScale: Self.waterScale)
        setCoolWaterModelMatrix(model)
    }

    /// Scaled to near-zero and parked well below the floor — CoolWater has no native
    /// visibility toggle, so a degenerate transform is the standard way to hide
    /// something that's always present in the render graph once installed.
    private static let hiddenWaterMatrix = simd_float4x4(
        waterTranslation: simd_float3(0, -1000, 0)
    ) * simd_float4x4(waterScale: simd_float3(repeating: 0.0001))

    // MARK: - Rotation

    /// Snap-rotate the selected entity by the given degrees around the Y axis.
    /// Captures the previous rotation so the action can be undone.
    func rotateSelectedEntityBy(degrees: Float) {
        guard let entity = selectedEntity else { return }
        let current = getAxisRotations(entityId: entity)
        pushUndo(.snapRotate(entityId: entity, previousRotations: current))
        applyAxisRotations(entityId: entity, axis: simd_float3(current.x, current.y + degrees, current.z))
    }

    /// Walk up the scenegraph to find which placed furniture root (if any)
    /// the picked entity belongs to. Handles multi-mesh hierarchical models.
    func placedFurnitureRoot(for entityId: EntityID) -> EntityID? {
        var current: EntityID? = entityId
        while let id = current {
            if placedFurnitureEntities.contains(id) { return id }
            current = getEntityParent(entityId: id)
        }
        return nil
    }

    // MARK: - Material Helpers

    /// Apply opacity and emissive to an entity and its entire descendant hierarchy.
    func applyMaterial(to entityId: EntityID, opacity: Float, emissive: simd_float3) {
        updateMaterialOpacity(entityId: entityId, opacity: opacity, recursive: true)
        updateMaterialEmmisive(entityId: entityId, emmissive: emissive, recursive: true)
    }

    /// Recursively list directory contents for debugging
    func listDirectoryRecursively(at url: URL, depth: Int = 0) {
        let indent = String(repeating: "  ", count: depth)
        guard let contents = try? FileManager.default.contentsOfDirectory(atPath: url.path) else {
            return
        }
        for item in contents {
            let itemURL = url.appendingPathComponent(item)
            var isDirectory: ObjCBool = false
            if FileManager.default.fileExists(atPath: itemURL.path, isDirectory: &isDirectory) {
                Logger.log(message: "\(indent)📁 \(item)\(isDirectory.boolValue ? "/" : "")")
                if isDirectory.boolValue && depth < 2 {
                    listDirectoryRecursively(at: itemURL, depth: depth + 1)
                }
            }
        }
    }

}

/// Name (prefix-matched — the engine may append e.g. ".root") of the node that marks
/// where a pool should be placed in a floor plan scene — a pure positioning proxy,
/// never itself rendered. Can be a standalone top-level entity or a named node inside
/// an imported multi-part asset (e.g. a SketchUp villa) — either is found by name once
/// the scene finishes loading.
let poolMarkerModelName = "pool"

/// The pool marker's transform relative to the floor-plan root, combined with the live
/// floor-plan and scene-root transforms every frame to get the water's world matrix.
struct PoolPlacement {
    var relativeTransform: simd_float4x4
}

private extension simd_float4x4 {
    init(waterTranslation t: simd_float3) {
        self.init(
            simd_float4(1, 0, 0, 0),
            simd_float4(0, 1, 0, 0),
            simd_float4(0, 0, 1, 0),
            simd_float4(t.x, t.y, t.z, 1)
        )
    }
    init(waterScale s: simd_float3) {
        self.init(
            simd_float4(s.x, 0, 0, 0),
            simd_float4(0, s.y, 0, 0),
            simd_float4(0, 0, s.z, 0),
            simd_float4(0, 0, 0, 1)
        )
    }
}
