//
//  GameScene.swift
//  HomeDesign
//
//  Generated by UntoldEngine Build System
//  visionOS Version
//

import Foundation
import simd
import UntoldEngine

// GameScene: Initialize your game and write game-specific logic
class GameScene {

    var placedFurnitureEntities: [EntityID] = []
    var furnitureModelNames: [EntityID: String] = [:]  // entity → model filename
    var wallItems: [EntityID: SpatialDragPlane] = [:]  // wall entity → drag plane
    var floorplanEntity: EntityID? = nil
    var pendingPlacementEntity: EntityID? = nil
    var pendingModelName: String? = nil              // model name for the in-flight placement
    var selectedEntity: EntityID? = nil
    var undoStack: [UndoAction] = []
    var lastReportedFloorPlanScale: Float = 1.0
    var calibrationComplete: Bool = false
    var calibratedFloorEntityY: Float = 0.0  // entity-space Y of floor plan floor (saved at calibration)
    var savedRealFloorY: Float = 0.0          // ARKit real-world floor Y (saved at calibration)
    var isMiniatureMode: Bool = false
    var isAnimatingScale: Bool = false
    var scaleAnimTarget: Float = 1.0
    var fullScaleScenePosition: simd_float3 = .zero

    init() {
        Logger.log(message: "🎮 GameScene initializing...")

        // Configure asset paths with debug logging
        logBundleInfo()
        setupAssetPaths()

        // Configure game Systems
        configureEngineSystems()

        // Load your scene here

        let floorplan = createEntity()
        floorplanEntity = floorplan
        setEntityMeshAsync(entityId: floorplan, filename: "FloorPlan", withExtension: "untold") { success in
            if success {
                // Start at miniature scale so the user can place it on their real floor.
                scaleSceneTo(0.05)
                setSceneReady(true)
            }
        }


    }

    // MARK: - Setup Methods

    /// Configure game Systems for play mode
    private func configureEngineSystems() {
        gameMode = true
        AnimationSystem.shared.isEnabled = true
        InputSystem.shared.registerXREvents()
        InputSystem.shared.setXRSpatialPickingBackendPreference(.octreeGPUPreferred)
        InputSystem.shared.setXRTwoHandRotateAxisMode(.dynamicSnapped)
        
        setRendering(.antiAliasing(.msaa))
        
        // Enables XR probe IBL lighting.
        setRendering(.environment(.lightingMode(.realWorldEstimate)))
        setRendering(.environment(.realWorldLightingContribution(0.3)))
        
    }

    // MARK: - Game Loop

    /// Called every frame - add custom game logic here
    func update(deltaTime _: Float) {
        if gameMode == false { return }

        // Animate the scene scale-in after the user taps to place the floor plan.
        animateScaleIn()

        // Track floor plan scale and notify SwiftUI when it changes.
        // Threshold avoids firing Task { @MainActor } every frame at 90 Hz.
        if let fp = floorplanEntity {
            let scale = getScale(entityId: fp).x
            if abs(scale - lastReportedFloorPlanScale) > 0.005 {
                lastReportedFloorPlanScale = scale
                HomeDesignStore.shared.notifyFloorPlanScaleChanged(scale)
            }
        }

        // Don't start a new load while an item is awaiting placement confirmation
        if isSceneReady() && pendingPlacementEntity == nil,
           let modelName = FurnitureLoadQueue.shared.dequeue() {
            loadFurnitureItem(modelName: modelName)
        }
    }

    /// Called for input handling - add custom input logic here
    func handleInput() {
        if gameMode == false { return }
        if isSceneReady() == false { return }

        let state = InputSystem.shared.xrSpatialInputState

        // ── Calibration mode ──────────────────────────────────────────────────
        // Wait for the user to tap their real floor before enabling normal input.
        // isAnimatingScale is also guarded so a second tap can't restart placement.
        if !calibrationComplete {
            if state.spatialTapActive, !isAnimatingScale {
                // .horizontalAny + Y-range is more robust than .floorOnly because
                // ARKit sometimes classifies the floor as .unknown early in a session.
                if let floorHit = pickRealSurfacePosition(
                    rayOrigin: state.rayOriginWorld,
                    rayDirection: state.rayDirectionWorld,
                    filter: .horizontalAny,
                    hitYRange: (-0.4)...0.2
                ) {
                    // If the ray also hit the floor plan miniature, convert that
                    // visual-world hit to entity space so we can offset the scene root:
                    // scene_position = floor_hit - entity_room_pos
                    // This places the tapped room at the user's real-world position,
                    // and also automatically compensates for the model's floor Y offset.
                    let roomEntityPos: simd_float3? = {
                        guard let pickedId = state.pickedEntityId,
                              let visualHit = state.pickedEntityWorldPosition,
                              isFloorplanDescendant(pickedId)
                        else { return nil }
                        return SceneRootTransform.shared.visualWorldToSceneLocal(visualHit)
                    }()

                    placeFloorPlanOnFloor(at: floorHit.worldPosition, room: roomEntityPos)
                }
            }
            return
        }

        if let pending = pendingPlacementEntity {
            // ── Placement mode ───────────────────────────────────────────────
            let srt = SceneRootTransform.shared
            let surface = HomeDesignStore.shared.placementSurface
            let snap = HomeDesignStore.shared.snapEnabled

            if surface == .wall {
                // Wall placement: project ray onto a vertical plane.
                // planeNormal  = horizontal gaze direction (approximates wall face).
                // planePoint   = where ray hits floor plan mesh; fallback 2 m in front.
                let gazeFlat = simd_float3(state.rayDirectionWorld.x, 0, state.rayDirectionWorld.z)
                if simd_length(gazeFlat) > 0.01 {
                    let wallNormal = simd_normalize(gazeFlat)
                    let wallPoint: simd_float3
                    if let hitVisual = state.pickedEntityWorldPosition,
                       let pickedId = state.pickedEntityId,
                       isFloorplanDescendant(pickedId) {
                        wallPoint = hitVisual
                    } else {
                        wallPoint = state.rayOriginWorld + simd_normalize(state.rayDirectionWorld) * 2.0
                    }
                    if let hit = pickPlanePosition(
                        rayOrigin: state.rayOriginWorld,
                        rayDirection: state.rayDirectionWorld,
                        planePoint: wallPoint,
                        planeNormal: wallNormal
                    ) {
                        var entityPos = srt.visualWorldToSceneLocal(hit.worldPosition)
                        if snap { entityPos = snapToGridXY(entityPos) }
                        translateTo(entityId: pending, position: entityPos)
                    }
                }
            } else {
                // Floor placement: project ray onto horizontal plane at the floor plan's surface.
                // visual_floor_Y = scene.position.y + scene.scale.y × calibratedFloorEntityY
                let planeY = srt.position.y + srt.scale.y * calibratedFloorEntityY
                if let hit = pickGroundPosition(
                    rayOrigin: state.rayOriginWorld,
                    rayDirection: state.rayDirectionWorld,
                    planeY: planeY
                ) {
                    var entityPos = srt.visualWorldToSceneLocal(hit.worldPosition)
                    if snap { entityPos = snapToGrid(entityPos) }
                    translateTo(entityId: pending, position: entityPos)
                }
            }

            // Tap confirms placement.
            // For wall items, detect orientation from gaze so the right drag plane is stored.
            if state.spatialTapActive {
                if surface == .wall {
                    let gazeFlat = simd_float3(state.rayDirectionWorld.x, 0, state.rayDirectionWorld.z)
                    let isEastWestFacing = abs(gazeFlat.x) >= abs(gazeFlat.z)
                    let dragPlane: SpatialDragPlane = isEastWestFacing ? .yz : .xy
                    confirmPlacement(pending, wallDragPlane: dragPlane)
                } else {
                    confirmPlacement(pending)
                }
            }

            // Skip normal pinch-drag processing while placing
            return
        }

        // ── Normal mode ──────────────────────────────────────────────────────

        // Consume any pending panel action from the UI
        if let action = HomeDesignStore.shared.consumeAction() {
            switch action {
            case .remove:               removeSelectedEntity()
            case .rotateLeft:           rotateSelectedEntityBy(degrees: -90)
            case .rotateRight:          rotateSelectedEntityBy(degrees: 90)
            case .duplicate:            duplicateSelectedEntity()
            case .resetFloorPlanScale:  resetFloorPlanScale()
            case .toggleMiniature:      toggleMiniatureMode(headPosition: state.rayOriginWorld,
                                                             gazeDirection: state.rayDirectionWorld)
            case .undo:                 performUndo()
            }
        }

        if state.spatialTapActive {
            if let entityId = state.pickedEntityId {
                if isFloorplanDescendant(entityId) {
                    if isMiniatureMode {
                        // Bird's eye: tap a room to enter it at full scale
                        if let visualHit = state.pickedEntityWorldPosition {
                            let entityRoomPos = SceneRootTransform.shared.visualWorldToSceneLocal(visualHit)
                            enterRoom(at: entityRoomPos, headPosition: state.rayOriginWorld)
                        }
                    } else {
                        // Full scale: tap teleports within the floor plan
                        if let hitPos = state.pickedEntityWorldPosition {
                            deselectEntity()
                            Logger.log(message: "Teleporting to: \(hitPos)")
                            translateSceneBy(delta: simd_float3(-hitPos.x, 0, -hitPos.z))
                        }
                    }
                } else if let root = placedFurnitureRoot(for: entityId) {
                    // Tap on placed furniture → toggle selection
                    if selectedEntity == root {
                        deselectEntity()
                    } else {
                        selectEntity(root)
                    }
                } else {
                    deselectEntity()
                }
            } else {
                // Tap on empty space → deselect
                deselectEntity()
            }
        }

        // Two-hand gestures: scale + rotate.
        // Priority: selected entity → furniture root under ray → floor plan (if looking at it)
        let twoHandTarget: EntityID?
        if let selected = selectedEntity {
            twoHandTarget = selected
        } else if let picked = state.pickedEntityId {
            if let furnitureRoot = placedFurnitureRoot(for: picked) {
                twoHandTarget = furnitureRoot
            } else if isFloorplanDescendant(picked) {
                twoHandTarget = floorplanEntity
            } else {
                twoHandTarget = nil
            }
        } else {
            twoHandTarget = nil
        }
        if let target = twoHandTarget {
            SpatialManipulationSystem.shared.applyTwoHandZoomIfNeeded(from: state, entityId: target)
            SpatialManipulationSystem.shared.applyTwoHandRotateIfNeeded(from: state, entityId: target)
        }

        // Single-hand pinch-drag with surface-aware plane and snap.
        // Wall items use their stored drag plane (.xy or .yz); floor items use .xz.
        if !state.spatialZoomActive && !state.spatialRotateActive {
            let dragTarget = selectedEntity
                ?? state.pickedEntityId.flatMap { placedFurnitureRoot(for: $0) }

            let dragPlane: SpatialDragPlane
            let snapFn: ((simd_float3) -> simd_float3)?

            if let target = dragTarget, let wallPlane = wallItems[target] {
                dragPlane = wallPlane
                if HomeDesignStore.shared.snapEnabled {
                    snapFn = wallPlane == .yz ? { snapToGridYZ($0) } : { snapToGridXY($0) }
                } else {
                    snapFn = nil
                }
            } else {
                dragPlane = .xz
                snapFn = HomeDesignStore.shared.snapEnabled ? { snapToGrid($0) } : nil
            }

            SpatialManipulationSystem.shared.processAnchoredPinchDragLifecycle(
                from: state,
                entityId: dragTarget,
                dragPlane: dragPlane,
                positionTransform: snapFn
            )
        } else {
            SpatialManipulationSystem.shared.endAnchoredPinchDrag()
        }
    }

}

@MainActor
final class EngineStatsWindowStore: ObservableObject {
    static let shared = EngineStatsWindowStore()

    @Published var advancedMode: Bool = false
    @Published private(set) var compactText: String = ""
    @Published private(set) var expandedText: String = ""

    private var timer: Timer?

    private init() {
        refresh()
        timer = Timer.scheduledTimer(withTimeInterval: 0.25, repeats: true) { [weak self] _ in
            guard let self else { return }
            Task { @MainActor in
                self.refresh()
            }
        }
    }

    deinit {
        timer?.invalidate()
    }

    private func refresh() {
        let snapshot = getEngineStatsSnapshot()
        compactText = formatEngineStatsCompact(snapshot)
        expandedText = formatEngineStatsOverlay(snapshot)
    }
}
