//
//  HomeDesignApp.swift
//  HomeDesign
//
//  Generated by UntoldEngine Build System
//  visionOS Version
//

import SwiftUI
import Combine
import Foundation
import CompositorServices
import UntoldEngineXR



// Simple owner so the XR system doesn't deallocate.
final class XRHolder {
    static let shared = XRHolder()
    var xr: UntoldEngineXR?
    var renderThread: Thread?
}

struct UntoldEngineConfiguration: CompositorLayerConfiguration {
    func makeConfiguration(capabilities: LayerRenderer.Capabilities,
                           configuration: inout LayerRenderer.Configuration) {
        configuration.layout = .dedicated
        configuration.isFoveationEnabled = false
        configuration.colorFormat = .bgra8Unorm_srgb
    }
}

@main
struct HomeDesignApp: App {

    @State private var immersionStyle: ImmersionStyle = .mixed

    var body: some Scene {
        WindowGroup {
            ContentView()
        }
        .windowStyle(.plain)
        .defaultSize(width: 600, height: 400)

        WindowGroup("Furniture", id: "FurniturePanel") {
            HomeItemsPanelView()
        }
        .defaultSize(width: 700, height: 520)

        WindowGroup("Engine Stats", id: "EngineStatsPanel") {
            EngineStatsWindowView(store: EngineStatsWindowStore.shared)
        }
        .defaultSize(width: 720, height: 340)

    ImmersiveSpace(id: "ImmersiveSpace") {

        CompositorLayer(configuration: UntoldEngineConfiguration(), renderer: { layerRenderer in

            // init + retain XR system
            if XRHolder.shared.xr == nil {

                if let xr = UntoldEngineXR(layerRenderer: layerRenderer) {
                    XRHolder.shared.xr = xr

                    // Set engine's immersion mode to mixed (passthrough)
                    xr.setImmersionMode(xrImmersionMode: .mixed)

                    // Initialize game scene
                    let gameScene = GameScene()

                    // Setup callbacks
                    xr.setupCallbacks(
                        gameUpdate: { deltaTime in
                            gameScene.update(deltaTime: deltaTime)
                        },
                        handleInput: {
                            gameScene.handleInput()
                        }
                    )

                    let t = Thread {
                        xr.start()      // sets isRunning = true
                        xr.runLoop()    // blocking loop - runs on dedicated thread, NOT MainActor
                    }
                    t.name = "XR Render Thread"
                    t.qualityOfService = .userInteractive
                    XRHolder.shared.renderThread = t
                    t.start()
                } else {
                    print("❌ Failed to initialize UntoldEngineXR!")
                    print("❌ LayerRenderer might be invalid or engine initialization failed")
                }
            } else {
                print("⚠️ XR system already initialized")
            }
        })
    }
        .immersionStyle(selection: $immersionStyle, in: .mixed)
    }
}

struct ContentView: View {
    @Environment(\.openImmersiveSpace) private var openImmersiveSpace
    @Environment(\.openWindow) private var openWindow
    @ObservedObject private var selectionStore = SelectionStore.shared
    @State private var experienceStarted = false

    var body: some View {
        VStack(spacing: 30) {
            Text("HomeDesign")
                .font(.extraLargeTitle)
                .fontWeight(.bold)

            Text("Powered by Untold Engine")
                .font(.title)
                .foregroundColor(.secondary)

            if !experienceStarted {
                // ── Pre-launch controls ──────────────────────────────────────
                Button(action: {
                    experienceStarted = true
                    Task { await openImmersiveSpace(id: "ImmersiveSpace") }
                }) {
                    Label("Start Experience", systemImage: "visionpro.fill")
                        .frame(minWidth: 250)
                }
                .buttonStyle(.borderedProminent)
                .controlSize(.large)

                Button { openWindow(id: "EngineStatsPanel") } label: {
                    Label("Engine Stats", systemImage: "chart.xyaxis.line")
                        .frame(minWidth: 250)
                }
                .buttonStyle(.bordered)
                .controlSize(.large)

            } else if !selectionStore.calibrationComplete {
                // ── Calibration prompt ───────────────────────────────────────
                VStack(spacing: 16) {
                    Image(systemName: "arrow.down.to.line.circle.fill")
                        .font(.system(size: 52))
                        .foregroundStyle(.tint)

                    Text("Look at your floor and tap\nto place the floor plan")
                        .font(.title2)
                        .fontWeight(.semibold)
                        .multilineTextAlignment(.center)

                    Text("Make sure you're standing in your room\nwith the floor visible.")
                        .font(.subheadline)
                        .foregroundStyle(.secondary)
                        .multilineTextAlignment(.center)
                }
                .padding(28)
                .background(.regularMaterial, in: RoundedRectangle(cornerRadius: 20))

            } else {
                // ── Post-calibration controls ────────────────────────────────

                // Room-entry hint shown while in bird's eye mode
                if selectionStore.isMiniatureMode {
                    VStack(spacing: 8) {
                        Image(systemName: "hand.tap.fill")
                            .font(.system(size: 32))
                            .foregroundStyle(.tint)
                        Text("Tap a room on the floor plan\nto enter it at full scale")
                            .font(.subheadline)
                            .fontWeight(.medium)
                            .multilineTextAlignment(.center)
                    }
                    .padding(20)
                    .background(.regularMaterial, in: RoundedRectangle(cornerRadius: 16))
                }

                if !selectionStore.isMiniatureMode {
                    Button { openWindow(id: "FurniturePanel") } label: {
                        Label("Furniture Catalog", systemImage: "sofa.fill")
                            .frame(minWidth: 250)
                    }
                    .buttonStyle(.borderedProminent)
                    .controlSize(.large)
                }

                Button {
                    HomeDesignStore.shared.requestAction(.toggleMiniature)
                } label: {
                    Label(
                        selectionStore.isMiniatureMode ? "Full Scale" : "Bird's Eye View",
                        systemImage: selectionStore.isMiniatureMode
                            ? "arrow.up.left.and.arrow.down.right"
                            : "binoculars.fill"
                    )
                    .frame(minWidth: 250)
                }
                .buttonStyle(.bordered)
                .controlSize(.large)

                Button { openWindow(id: "EngineStatsPanel") } label: {
                    Label("Engine Stats", systemImage: "chart.xyaxis.line")
                        .frame(minWidth: 250)
                }
                .buttonStyle(.bordered)
                .controlSize(.large)
            }
        }
        .padding(60)
        .animation(.spring(response: 0.4), value: experienceStarted)
        .animation(.spring(response: 0.4), value: selectionStore.calibrationComplete)
    }
}

struct EngineStatsWindowView: View {
    @ObservedObject var store: EngineStatsWindowStore

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack {
                Text("Engine Stats")
                    .font(.headline)
                Spacer()
                Toggle("Advanced", isOn: $store.advancedMode)
                    .toggleStyle(.switch)
                    .controlSize(.small)
            }

            ScrollView {
                Text(store.advancedMode ? store.expandedText : store.compactText)
                    .font(.system(size: 12, design: .monospaced))
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .textSelection(.enabled)
            }
        }
        .padding(16)
    }
}