//
//  GameScene.swift
//  CityStreaming
//
//  Generated by UntoldEngine Build System
//  visionOS Version
//

import Foundation
import simd
import UntoldEngine

// GameScene: Initialize your game and write game-specific logic
class GameScene {

    private let maxTeleportDistanceMeters: Float = 40.0
    
    init() {
        Logger.log(message: "🎮 GameScene initializing...")

        // Configure asset paths with debug logging
        logBundleInfo()
        setupAssetPaths()

        // Configure game Systems
        configureEngineSystems()
        configureCityStreaming()

        // Load your scene here

        let cityRoot = createEntity()
        setEntityName(entityId: cityRoot, name: "LowPolyCity")

        setEntityStreamScene(entityId: cityRoot, manifest: "LowPolyCity", withExtension: "json") { success in
            translateBy(entityId: cityRoot, position: simd_float3(0.0,-6.0,0.0))
            setSceneReady(success)
        }


    }

    // MARK: - Setup Methods

    /// Configure game Systems for play mode
    private func configureEngineSystems() {
        gameMode = true
        AnimationSystem.shared.isEnabled = true
        InputSystem.shared.registerXREvents()
        InputSystem.shared.setXRSpatialPickingBackendPreference(.octreeGPUPreferred)
        InputSystem.shared.setXRTwoHandRotateAxisMode(.dynamicSnapped)
    }
    
    private func configureCityStreaming() {
        setGeometryStreaming(.enabled(true))
    }

    // MARK: - Game Loop

    /// Called every frame - add custom game logic here
    func update(deltaTime _: Float) {
        // Skip logic if not in game mode
        if gameMode == false { return }

        // Add your custom update logic here
    }

    /// Called for input handling - add custom input logic here
    func handleInput() {
        // Skip logic if not in game mode
        guard gameMode, isSceneReady() else { return }

        let state = getXRSpatialInputState()

        // Tap a walkable surface to teleport there.
        if state.spatialTapActive,
           let hitPos = state.pickedEntityWorldPosition,
           let normal = state.pickedEntityWorldNormal,
           isWalkable(normal),
           isWithinTeleportRange(hitPos)
        {
            translateSceneBy(delta: simd_float3(-hitPos.x, 0, -hitPos.z))
        }

        // Pinch + drag to move the scene root; two-hand pinch to rotate it.
        SpatialManipulationSystem.shared.processAnchoredSceneManipulationLifecycle(
            from: state,
            dragSensitivity: 10.0,
            rotateSensitivity: 1.0
        )

        // Add your custom input handling here
    }
    
    private func isWalkable(_ normal: simd_float3) -> Bool {
        let slope = acos(simd_clamp(simd_dot(simd_normalize(normal), simd_float3(0, 1, 0)), -1, 1))
        return slope <= (.pi / 6) // ~30°, rejects building facades/walls
    }

    private func isWithinTeleportRange(_ hitPos: simd_float3) -> Bool {
        simd_length(simd_float3(hitPos.x, 0, hitPos.z)) <= maxTeleportDistanceMeters
    }

}

@MainActor
final class EngineStatsWindowStore: ObservableObject {
    static let shared = EngineStatsWindowStore()

    @Published var advancedMode: Bool = false
    @Published private(set) var compactText: String = ""
    @Published private(set) var expandedText: String = ""

    private var timer: Timer?

    private init() {
        refresh()
        timer = Timer.scheduledTimer(withTimeInterval: 0.25, repeats: true) { [weak self] _ in
            guard let self else { return }
            Task { @MainActor in
                self.refresh()
            }
        }
    }

    deinit {
        timer?.invalidate()
    }

    private func refresh() {
        let snapshot = getEngineStatsSnapshot()
        compactText = formatEngineStatsCompact(snapshot)
        expandedText = formatEngineStatsOverlay(snapshot)
    }
}
