//
//  GameScene.swift
//  CoolFutbol
//
//  Copyright (C) Untold Engine Studios
//  Licensed under the GNU LGPL v3.0 or later.
//  See the LICENSE file or <https://www.gnu.org/licenses/> for details.
//
//  Generated by UntoldEngine Build System
//  visionOS Version
//

import Foundation
import simd
import UntoldEngine

// GameScene: Initialize your game and write game-specific logic
class GameScene {

    // MARK: - Placement (M1)

    private enum DemoPhase {
        case locating   // waiting for a pinch aimed at a real table
        case placing    // position locked to the table; rotate + tap to confirm
        case locked     // placement confirmed — scene root transform is frozen
    }

    private var phase: DemoPhase = .locating
    private var stadiumEntityId: EntityID?
    private var wasPinching = false
    // True right after entering .placing, until the pinch that triggered the
    // table snap has fully released — suppresses that pinch's trailing tap.
    private var awaitingPinchReleaseBeforeConfirm = false

    // Confirmed on-device: tabletop-sized stadium.
    private let defaultSceneScale: Float = 0.02
    // Ghost opacity while the stadium is still being positioned.
    private let placementPreviewOpacity: Float = 0.2

    init() {
        Logger.log(message: "🎮 GameScene initializing...")

        // Configure asset paths with debug logging
        logBundleInfo()
        setupAssetPaths()

        // Configure game Systems
        configureEngineSystems()

        // Load the futbol scene (stadium, camera, lighting).
        loadUntoldScene(named: "futbol") { [weak self] success in
            setSceneReady(success)
            guard success else {
                Logger.log(message: "⚠️ GameScene: Failed to load futbol.untoldscene")
                return
            }
            guard let self else { return }

            SceneRootTransform.shared.reset()
            SceneRootTransform.shared.scale = .init(repeating: self.defaultSceneScale)

            self.stadiumEntityId = findEntity(name: "Stadium")
            if let stadium = self.stadiumEntityId {
                Logger.log(message: "✅ Stadium entity found at \(getPosition(entityId: stadium))")
                updateMaterialOpacity(entityId: stadium, opacity: self.placementPreviewOpacity, recursive: true)
            } else {
                Logger.log(message: "⚠️ GameScene: Could not find 'Stadium' entity in scene")
            }

            self.setGuidance("Look at your table and pinch to place the stadium there.")
        }
    }

    // MARK: - Setup Methods

    /// Configure game Systems for play mode
    private func configureEngineSystems() {
        let  sun = createEntity()
        createDirLight(entityId: sun)
       
        setLight(entityId: sun, .intensity(0.4))
        setLight(entityId: sun, .directional(.active))
        
        gameMode = true
        AnimationSystem.shared.isEnabled = true
        InputSystem.shared.registerXREvents()
        InputSystem.shared.setXRSpatialPickingBackendPreference(.octreeGPUPreferred)
        InputSystem.shared.setXRTwoHandRotateAxisMode(.dynamicSnapped)
        setRendering(.maxShadowCastingDistance(2.0))
        
        setRendering(.antiAliasing(.msaa))
    }

    // MARK: - Game Loop

    /// Called every frame - add custom game logic here
    func update(deltaTime _: Float) {
        // Skip logic if not in game mode
        if gameMode == false { return }
    }

    /// Called for input handling - add custom input logic here
    func handleInput() {
        // Skip logic if not in game mode
        if gameMode == false { return }
        if isSceneReady() == false { return }

        let state = InputSystem.shared.xrSpatialInputState

        switch phase {
        case .locating:
            handleLocatingInput(state)
        case .placing:
            handlePlacingInput(state)
        case .locked:
            break
        }

        wasPinching = state.spatialPinchActive
    }

    // MARK: - Placement input (M1)

    /// Waiting for the user to pinch while looking at a real table. There is no
    /// continuous gaze ray available (the engine only gives us a ray during an
    /// active pinch), so detection happens on the pinch itself rather than live.
    private func handleLocatingInput(_ state: XRSpatialInputState) {
        let pinchBegan = state.spatialPinchActive && !wasPinching
        guard pinchBegan else { return }

        guard isFiniteVector(state.rayOriginWorld),
              isFiniteVector(state.rayDirectionWorld),
              simd_length_squared(state.rayDirectionWorld) > 0.0001
        else {
            setGuidance("No aim direction available — try pinching again.")
            return
        }

        // NOTE: maxDistance is intentionally omitted (defaults to unlimited).
        // pickRealSurfacePosition compares its internal local-space distance
        // (scaled by the inverse of SceneRootTransform.scale) directly against
        // maxDistance, which the API documents as real-world meters. With our
        // scene root scaled to 0.01, that local-space distance is ~100x real
        // meters, so any finite maxDistance we pass rejects every real hit.
        // Passing no maxDistance sidesteps the mismatched comparison; the
        // closest-hit selection (distance < bestDistance) is unaffected since
        // both sides of that comparison are consistently in local space.
        let hit = pickRealSurfacePosition(
            rayOrigin: state.rayOriginWorld,
            rayDirection: state.rayDirectionWorld,
            filter: .tableOnly
        ) ?? pickRealSurfacePosition(
            rayOrigin: state.rayOriginWorld,
            rayDirection: state.rayDirectionWorld,
            filter: .horizontalAny
        ) ?? pickRealSurfacePosition(
            rayOrigin: state.rayOriginWorld,
            rayDirection: state.rayDirectionWorld,
            filter: .any
        )

        guard let hit else {
            setGuidance("No surface detected there — look directly at your table and pinch again.")
            return
        }

        SceneRootTransform.shared.position = hit.worldPosition
        phase = .placing
        // The pinch that just confirmed the table hit also reads as a tap on
        // release (a short pinch == a tap). Ignore taps until that same pinch
        // has fully released, so it can't immediately confirm placement too.
        awaitingPinchReleaseBeforeConfirm = true
        setGuidance("Two-hand pinch to rotate. Tap to confirm placement.")
        Logger.log(message: "📍 Snapped to \(hit.surfaceKind) plane at \(hit.worldPosition)")
    }

    /// Position is locked to the table; only rotation is available before the final confirm tap.
    private func handlePlacingInput(_ state: XRSpatialInputState) {
        if awaitingPinchReleaseBeforeConfirm {
            if !state.spatialPinchActive {
                awaitingPinchReleaseBeforeConfirm = false
            }
        } else if state.spatialTapActive {
            confirmPlacement()
            return
        }

        SpatialManipulationSystem.shared.processAnchoredSceneRotateLifecycle(from: state, sensitivity: 1.0)
    }

    private func confirmPlacement() {
        phase = .locked
        SpatialManipulationSystem.shared.endAnchoredSceneRotate()
        if let stadium = stadiumEntityId {
            updateMaterialOpacity(entityId: stadium, opacity: 1.0, recursive: true)
        }
        setGuidance("Placement confirmed!")
        Logger.log(message: "📍 Placement confirmed — scene root locked at scale \(SceneRootTransform.shared.scale)")

        startGameplay()
    }

    // MARK: - Gameplay bootstrap (M2 — first iteration: one controllable player + ball)

    /// Ball and player are authored directly in futbol.untoldscene (same
    /// pattern as Stadium) — position, mesh, and physics/kinetics are set up
    /// there, not in code. This just finds them and layers the gameplay
    /// components on top.
    private func startGameplay() {
        loadSceneManifest()
        loadGameplayTuning()

        guard let ball = findEntity(name: "Ball") else {
            Logger.log(message: "⚠️ GameScene: Could not find 'Ball' entity in scene — add it in the scene editor first")
            return
        }
        setEntityKinetics(entityId: ball)
        registerComponent(entityId: ball, componentType: BallComponent.self)
        registerComponent(entityId: ball, componentType: BallPossessionComponent.self)

        // Configure every player listed in every team's roster — no formation/AI
        // positioning yet, so non-controlled players just stand at their
        // scene-authored spot until passed to or manually switched onto.
        var controlledPlayer: EntityID?
        for team in SceneManifest.shared.teams {
            for (index, playerEntry) in team.players.enumerated() {
                guard let configured = configurePlayer(
                    named: playerEntry.entityName,
                    team: team.team,
                    side: team.side,
                    animations: team.animations,
                    role: playerEntry.role
                ) else { return }

                if index == team.playerControlledIndex {
                    controlledPlayer = configured
                }
            }
        }

        guard let controlledPlayer else {
            Logger.log(message: "⚠️ GameScene: No team has a valid playerControlledIndex — nobody is controlled")
            return
        }

        EntityRegistry.shared.initialize()
        EntityRegistry.shared.setPlayerControlled(controlledPlayer)

        registerCustomSystem(ballPossessionSystemUpdate)
        registerCustomSystem(playerStateSystemUpdate)
        registerCustomSystem(dribblingSystemUpdate)
        registerCustomSystem(shootingSystemUpdate)
        registerCustomSystem(passingSystemUpdate)
        registerCustomSystem(receivingSystemUpdate)
        registerCustomSystem(ballSystemUpdate)
        // Formation shape-holding: matchState (possession → attack/defend) must
        // run before tacticalSubPhase (press/transition timer on top of that),
        // which must run before fieldFormation (reads both to pick cell layout).
        registerCustomSystem(matchStateSystemUpdate)
        registerCustomSystem(tacticalSubPhaseSystemUpdate)
        registerCustomSystem(fieldFormationSystemUpdate)

        setGuidance("Use the controller to run around the pitch.")
        Logger.log(message: "⚽️ M2 gameplay started")
    }

    /// Finds a player entity authored in the scene and layers the gameplay
    /// components on top (same pattern as Ball). Every player gets the full
    /// component set — DribblingComponent/ShootingComponent/PassingComponent —
    /// since control (and therefore dribbling/shooting) can hand off to any
    /// teammate once they receive a pass.
    private func configurePlayer(
        named entityName: String,
        team: Team,
        side: MatchSide,
        animations: [SceneManifest.AnimationEntry],
        role: FormationRole
    ) -> EntityID? {
        guard let player = findEntity(name: entityName) else {
            Logger.log(message: "⚠️ GameScene: Could not find '\(entityName)' entity in scene — add it in the scene editor first")
            return nil
        }
        setEntityKinetics(entityId: player)
        for animation in animations {
            setEntityAnimations(entityId: player, filename: animation.file, withExtension: "untold", name: animation.name)
        }
        changeAnimation(entityId: player, name: "idle")

        registerComponent(entityId: player, componentType: PlayerStateComponent.self)
        registerComponent(entityId: player, componentType: DribblingComponent.self)
        registerComponent(entityId: player, componentType: PlayerControlComponent.self)
        registerComponent(entityId: player, componentType: TeamComponent.self)
        registerComponent(entityId: player, componentType: ShootingComponent.self)
        registerComponent(entityId: player, componentType: PassingComponent.self)
        registerComponent(entityId: player, componentType: PlayerRoleComponent.self)
        if let teamComponent = scene.get(component: TeamComponent.self, for: player) {
            teamComponent.team = team
            teamComponent.side = side
        }
        if let roleComponent = scene.get(component: PlayerRoleComponent.self, for: player) {
            roleComponent.role = role
        }

        return player
    }

    private func setGuidance(_ message: String) {
        Task { @MainActor in
            PlacementGuideStore.shared.message = message
        }
    }

    private func isFiniteVector(_ vector: simd_float3) -> Bool {
        vector.x.isFinite && vector.y.isFinite && vector.z.isFinite
    }

}

@MainActor
final class PlacementGuideStore: ObservableObject {
    static let shared = PlacementGuideStore()

    @Published var message: String = "Look around for a flat surface like a table."

    private init() {}
}

@MainActor
final class EngineStatsWindowStore: ObservableObject {
    static let shared = EngineStatsWindowStore()

    @Published var advancedMode: Bool = false
    @Published private(set) var compactText: String = ""
    @Published private(set) var expandedText: String = ""

    private var timer: Timer?

    private init() {
        refresh()
        timer = Timer.scheduledTimer(withTimeInterval: 0.25, repeats: true) { [weak self] _ in
            guard let self else { return }
            Task { @MainActor in
                self.refresh()
            }
        }
    }

    deinit {
        timer?.invalidate()
    }

    private func refresh() {
        let snapshot = getEngineStatsSnapshot()
        compactText = formatEngineStatsCompact(snapshot)
        expandedText = formatEngineStatsOverlay(snapshot)
    }
}
