//
//  GameScene.swift
//  CoolFutbol
//
//  Generated by UntoldEngine Build System
//  visionOS Version
//

import Foundation
import simd
import UntoldEngine

// GameScene: Initialize your game and write game-specific logic
class GameScene {

    // MARK: - Placement (M1)

    private enum DemoPhase {
        case placing   // stadium can be dragged / rotated / scaled by the user
        case locked    // placement confirmed — scene root transform is frozen
    }

    private var phase: DemoPhase = .placing
    private var stadiumEntityId: EntityID?

    // Tunables — expect to adjust these once you've seen scale/position on-device.
    private let sceneScaleSensitivity: Float = 1.0
    private let minSceneScale: Float = 0.01
    private let maxSceneScale: Float = 2.0
    // Confirmed on-device: tabletop-sized stadium.
    private let defaultSceneScale: Float = 0.01

    init() {
        Logger.log(message: "🎮 GameScene initializing...")

        // Configure asset paths with debug logging
        logBundleInfo()
        setupAssetPaths()

        // Configure game Systems
        configureEngineSystems()

        // Load the futbol scene (stadium, camera, lighting).
        loadUntoldScene(named: "futbol") { [weak self] success in
            setSceneReady(success)
            guard success else {
                Logger.log(message: "⚠️ GameScene: Failed to load futbol.untoldscene")
                return
            }
            guard let self else { return }

            SceneRootTransform.shared.reset()
            SceneRootTransform.shared.scale = .init(repeating: self.defaultSceneScale)

            self.stadiumEntityId = findEntity(name: "Stadium")
            if let stadium = self.stadiumEntityId {
                Logger.log(message: "✅ Stadium entity found at \(getPosition(entityId: stadium))")
            } else {
                Logger.log(message: "⚠️ GameScene: Could not find 'Stadium' entity in scene")
            }
        }
    }

    // MARK: - Setup Methods

    /// Configure game Systems for play mode
    private func configureEngineSystems() {
        gameMode = true
        AnimationSystem.shared.isEnabled = true
        InputSystem.shared.registerXREvents()
        InputSystem.shared.setXRSpatialPickingBackendPreference(.octreeGPUPreferred)
        InputSystem.shared.setXRTwoHandRotateAxisMode(.dynamicSnapped)
    }

    // MARK: - Game Loop

    /// Called every frame - add custom game logic here
    func update(deltaTime _: Float) {
        // Skip logic if not in game mode
        if gameMode == false { return }

        // Add your custom update logic here
    }

    /// Called for input handling - add custom input logic here
    func handleInput() {
        // Skip logic if not in game mode
        if gameMode == false { return }
        if isSceneReady() == false { return }

        let state = InputSystem.shared.xrSpatialInputState

        switch phase {
        case .placing:
            handlePlacementInput(state)
        case .locked:
            break
        }
    }

    // MARK: - Placement input (M1)

    private func handlePlacementInput(_ state: XRSpatialInputState) {
        // Tap anywhere to confirm placement and lock the scene-root transform.
        // (Not gated to the exact "Stadium" entity — the model's child sub-meshes
        // are what actually get hit by the raycast, not the parent entity.)
        if state.spatialTapActive {
            confirmPlacement()
            return
        }

        // Pinch + drag to move the scene root; two-hand pinch to rotate it.
        SpatialManipulationSystem.shared.processAnchoredSceneManipulationLifecycle(
            from: state,
            dragSensitivity: 10.0,
            rotateSensitivity: 1.0
        )

        // Two-hand pinch pull apart/together to scale the whole scene root
        // (shrinks the full-size pitch down to tabletop size).
        updateSceneScaleGesture(state)
    }

    private func updateSceneScaleGesture(_ state: XRSpatialInputState) {
        guard state.leftHandPinching, state.rightHandPinching, state.spatialZoomActive else { return }

        let zoomDelta = state.spatialZoomDelta * sceneScaleSensitivity
        guard zoomDelta.isFinite, abs(zoomDelta) > .ulpOfOne else { return }

        let scaleFactor = max(0, 1 + zoomDelta)
        var newScale = SceneRootTransform.shared.scale * scaleFactor
        newScale = simd_clamp(newScale, .init(repeating: minSceneScale), .init(repeating: maxSceneScale))
        guard newScale.x.isFinite, newScale.y.isFinite, newScale.z.isFinite else { return }

        SceneRootTransform.shared.scale = newScale
    }

    private func confirmPlacement() {
        phase = .locked
        SpatialManipulationSystem.shared.endAnchoredSceneManipulation()
        Logger.log(message: "📍 Placement confirmed — scene root locked at scale \(SceneRootTransform.shared.scale)")
    }

}

@MainActor
final class EngineStatsWindowStore: ObservableObject {
    static let shared = EngineStatsWindowStore()

    @Published var advancedMode: Bool = false
    @Published private(set) var compactText: String = ""
    @Published private(set) var expandedText: String = ""

    private var timer: Timer?

    private init() {
        refresh()
        timer = Timer.scheduledTimer(withTimeInterval: 0.25, repeats: true) { [weak self] _ in
            guard let self else { return }
            Task { @MainActor in
                self.refresh()
            }
        }
    }

    deinit {
        timer?.invalidate()
    }

    private func refresh() {
        let snapshot = getEngineStatsSnapshot()
        compactText = formatEngineStatsCompact(snapshot)
        expandedText = formatEngineStatsOverlay(snapshot)
    }
}
