//
//  GameScene.swift
//  CoolFutbol
//
//  Generated by UntoldEngine Build System
//  visionOS Version
//

import Foundation
import simd
import UntoldEngine

// GameScene: Initialize your game and write game-specific logic
class GameScene {

    // MARK: - Placement (M1)

    private enum DemoPhase {
        case locating   // waiting for a pinch aimed at a real table
        case placing    // position locked to the table; rotate + tap to confirm
        case locked     // placement confirmed — scene root transform is frozen
    }

    private var phase: DemoPhase = .locating
    private var stadiumEntityId: EntityID?
    private var wasPinching = false
    // True right after entering .placing, until the pinch that triggered the
    // table snap has fully released — suppresses that pinch's trailing tap.
    private var awaitingPinchReleaseBeforeConfirm = false

    // Confirmed on-device: tabletop-sized stadium.
    private let defaultSceneScale: Float = 0.01
    // Ghost opacity while the stadium is still being positioned.
    private let placementPreviewOpacity: Float = 0.2

    // Debug: periodically dump detected real-world planes to the console
    // during placement, to verify plane detection is finding the table.
    private var planeLogElapsed: Float = 0
    private let planeLogInterval: Float = 2.0

    init() {
        Logger.log(message: "🎮 GameScene initializing...")

        // Configure asset paths with debug logging
        logBundleInfo()
        setupAssetPaths()

        // Configure game Systems
        configureEngineSystems()

        // Load the futbol scene (stadium, camera, lighting).
        loadUntoldScene(named: "futbol") { [weak self] success in
            setSceneReady(success)
            guard success else {
                Logger.log(message: "⚠️ GameScene: Failed to load futbol.untoldscene")
                return
            }
            guard let self else { return }

            SceneRootTransform.shared.reset()
            SceneRootTransform.shared.scale = .init(repeating: self.defaultSceneScale)

            self.stadiumEntityId = findEntity(name: "Stadium")
            if let stadium = self.stadiumEntityId {
                Logger.log(message: "✅ Stadium entity found at \(getPosition(entityId: stadium))")
                updateMaterialOpacity(entityId: stadium, opacity: self.placementPreviewOpacity, recursive: true)
            } else {
                Logger.log(message: "⚠️ GameScene: Could not find 'Stadium' entity in scene")
            }

            self.setGuidance("Look at your table and pinch to place the stadium there.")
        }
    }

    // MARK: - Setup Methods

    /// Configure game Systems for play mode
    private func configureEngineSystems() {
        gameMode = true
        AnimationSystem.shared.isEnabled = true
        InputSystem.shared.registerXREvents()
        InputSystem.shared.setXRSpatialPickingBackendPreference(.octreeGPUPreferred)
        InputSystem.shared.setXRTwoHandRotateAxisMode(.dynamicSnapped)
    }

    // MARK: - Game Loop

    /// Called every frame - add custom game logic here
    func update(deltaTime deltaTime: Float) {
        // Skip logic if not in game mode
        if gameMode == false { return }

        // Debug: confirm plane detection is finding/classifying real surfaces.
        if phase == .locating {
            planeLogElapsed += deltaTime
            if planeLogElapsed >= planeLogInterval {
                planeLogElapsed = 0
                RealSurfacePlaneStore.shared.logAllPlanes()
            }
        }
    }

    /// Called for input handling - add custom input logic here
    func handleInput() {
        // Skip logic if not in game mode
        if gameMode == false { return }
        if isSceneReady() == false { return }

        let state = InputSystem.shared.xrSpatialInputState

        switch phase {
        case .locating:
            handleLocatingInput(state)
        case .placing:
            handlePlacingInput(state)
        case .locked:
            break
        }

        wasPinching = state.spatialPinchActive
    }

    // MARK: - Placement input (M1)

    /// Waiting for the user to pinch while looking at a real table. There is no
    /// continuous gaze ray available (the engine only gives us a ray during an
    /// active pinch), so detection happens on the pinch itself rather than live.
    private func handleLocatingInput(_ state: XRSpatialInputState) {
        let pinchBegan = state.spatialPinchActive && !wasPinching
        guard pinchBegan else { return }

        // Diagnostics: confirm whether ARKit has any planes at all, and whether
        // the ray we're about to cast is actually usable.
        let planeCount = RealSurfacePlaneStore.shared.snapshot().count
        Logger.log(message: "🔍 Pinch sample: planes=\(planeCount) origin=\(state.rayOriginWorld) direction=\(state.rayDirectionWorld)")
        Logger.log(message: "🔍 SceneRootTransform: isIdentity=\(SceneRootTransform.shared.isIdentity) position=\(SceneRootTransform.shared.position) scale=\(SceneRootTransform.shared.scale)")
        RealSurfacePlaneStore.shared.logAllPlanes()

        guard isFiniteVector(state.rayOriginWorld),
              isFiniteVector(state.rayDirectionWorld),
              simd_length_squared(state.rayDirectionWorld) > 0.0001
        else {
            setGuidance("No aim direction available — try pinching again.")
            Logger.log(message: "⚠️ Invalid/empty ray on pinch — origin or direction non-finite or zero")
            return
        }

        // NOTE: maxDistance is intentionally omitted (defaults to unlimited).
        // pickRealSurfacePosition compares its internal local-space distance
        // (scaled by the inverse of SceneRootTransform.scale) directly against
        // maxDistance, which the API documents as real-world meters. With our
        // scene root scaled to 0.01, that local-space distance is ~100x real
        // meters, so any finite maxDistance we pass rejects every real hit.
        // Passing no maxDistance sidesteps the mismatched comparison; the
        // closest-hit selection (distance < bestDistance) is unaffected since
        // both sides of that comparison are consistently in local space.
        let tableHit = pickRealSurfacePosition(
            rayOrigin: state.rayOriginWorld,
            rayDirection: state.rayDirectionWorld,
            filter: .tableOnly
        )
        Logger.log(message: tableHit != nil
            ? "✅ .tableOnly hit at \(tableHit!.worldPosition)"
            : "❌ .tableOnly found nothing")

        let horizontalHit = pickRealSurfacePosition(
            rayOrigin: state.rayOriginWorld,
            rayDirection: state.rayDirectionWorld,
            filter: .horizontalAny
        )
        Logger.log(message: horizontalHit != nil
            ? "✅ .horizontalAny hit kind=\(horizontalHit!.surfaceKind) at \(horizontalHit!.worldPosition)"
            : "❌ .horizontalAny found nothing either")

        let anyFilterHit = pickRealSurfacePosition(
            rayOrigin: state.rayOriginWorld,
            rayDirection: state.rayDirectionWorld,
            filter: .any
        )
        Logger.log(message: anyFilterHit != nil
            ? "✅ .any hit kind=\(anyFilterHit!.surfaceKind) alignment-unfiltered at \(anyFilterHit!.worldPosition)"
            : "❌ .any (no alignment/kind filter at all) found nothing")

        guard let hit = tableHit ?? horizontalHit ?? anyFilterHit else {
            setGuidance("No surface detected there — look directly at your table and pinch again.")
            return
        }

        SceneRootTransform.shared.position = hit.worldPosition
        phase = .placing
        // The pinch that just confirmed the table hit also reads as a tap on
        // release (a short pinch == a tap). Ignore taps until that same pinch
        // has fully released, so it can't immediately confirm placement too.
        awaitingPinchReleaseBeforeConfirm = true
        setGuidance("Two-hand pinch to rotate. Tap to confirm placement.")
        Logger.log(message: "📍 Snapped to \(hit.surfaceKind) plane at \(hit.worldPosition)")
    }

    /// Position is locked to the table; only rotation is available before the final confirm tap.
    private func handlePlacingInput(_ state: XRSpatialInputState) {
        if awaitingPinchReleaseBeforeConfirm {
            if !state.spatialPinchActive {
                awaitingPinchReleaseBeforeConfirm = false
            }
        } else if state.spatialTapActive {
            confirmPlacement()
            return
        }

        SpatialManipulationSystem.shared.processAnchoredSceneRotateLifecycle(from: state, sensitivity: 1.0)
    }

    private func confirmPlacement() {
        phase = .locked
        SpatialManipulationSystem.shared.endAnchoredSceneRotate()
        if let stadium = stadiumEntityId {
            updateMaterialOpacity(entityId: stadium, opacity: 1.0, recursive: true)
        }
        setGuidance("Placement confirmed!")
        Logger.log(message: "📍 Placement confirmed — scene root locked at scale \(SceneRootTransform.shared.scale)")
    }

    private func setGuidance(_ message: String) {
        Task { @MainActor in
            PlacementGuideStore.shared.message = message
        }
    }

    private func isFiniteVector(_ vector: simd_float3) -> Bool {
        vector.x.isFinite && vector.y.isFinite && vector.z.isFinite
    }

}

@MainActor
final class PlacementGuideStore: ObservableObject {
    static let shared = PlacementGuideStore()

    @Published var message: String = "Look around for a flat surface like a table."

    private init() {}
}

@MainActor
final class EngineStatsWindowStore: ObservableObject {
    static let shared = EngineStatsWindowStore()

    @Published var advancedMode: Bool = false
    @Published private(set) var compactText: String = ""
    @Published private(set) var expandedText: String = ""

    private var timer: Timer?

    private init() {
        refresh()
        timer = Timer.scheduledTimer(withTimeInterval: 0.25, repeats: true) { [weak self] _ in
            guard let self else { return }
            Task { @MainActor in
                self.refresh()
            }
        }
    }

    deinit {
        timer?.invalidate()
    }

    private func refresh() {
        let snapshot = getEngineStatsSnapshot()
        compactText = formatEngineStatsCompact(snapshot)
        expandedText = formatEngineStatsOverlay(snapshot)
    }
}
