//
//  BedroomTwinApp.swift
//  BedroomTwin
//
//  Generated by UntoldEngine Build System
//  visionOS Version
//

import SwiftUI
import Combine
import Foundation
import CompositorServices
import UntoldEngineXR



// Simple owner so the XR system doesn't deallocate.
final class XRHolder {
    static let shared = XRHolder()
    var xr: UntoldEngineXR?
    var renderThread: Thread?
}

struct UntoldEngineConfiguration: CompositorLayerConfiguration {
    func makeConfiguration(capabilities: LayerRenderer.Capabilities,
                           configuration: inout LayerRenderer.Configuration) {
        configuration.layout = .dedicated
        configuration.isFoveationEnabled = false
        configuration.colorFormat = .bgra8Unorm_srgb
    }
}

@main
struct BedroomTwinApp: App {

    @State private var immersionStyle: ImmersionStyle = .mixed

    var body: some Scene {
        WindowGroup {
            ContentView()
        }
        .windowStyle(.plain)
        .defaultSize(width: 600, height: 400)

        WindowGroup("Engine Stats", id: "EngineStatsPanel") {
            EngineStatsWindowView(store: EngineStatsWindowStore.shared)
        }
        .defaultSize(width: 720, height: 340)

        WindowGroup("Object Info", id: "TwinInfoPanel") {
            TwinInfoWindowView(store: TwinInfoWindowStore.shared)
        }
        .defaultSize(width: 420, height: 260)

    ImmersiveSpace(id: "ImmersiveSpace") {

        CompositorLayer(configuration: UntoldEngineConfiguration(), renderer: { layerRenderer in

            // init + retain XR system
            if XRHolder.shared.xr == nil {

                if let xr = UntoldEngineXR(layerRenderer: layerRenderer) {
                    XRHolder.shared.xr = xr

                    // Set engine's immersion mode to mixed (passthrough)
                    xr.setImmersionMode(xrImmersionMode: .mixed)

                    // Initialize game scene
                    let gameScene = GameScene()

                    // Setup callbacks
                    xr.setupCallbacks(
                        gameUpdate: { deltaTime in
                            gameScene.update(deltaTime: deltaTime)
                        },
                        handleInput: {
                            gameScene.handleInput()
                        }
                    )

                    let t = Thread {
                        xr.start()      // sets isRunning = true
                        xr.runLoop()    // blocking loop - runs on dedicated thread, NOT MainActor
                    }
                    t.name = "XR Render Thread"
                    t.qualityOfService = .userInteractive
                    XRHolder.shared.renderThread = t
                    t.start()
                } else {
                    print("❌ Failed to initialize UntoldEngineXR!")
                    print("❌ LayerRenderer might be invalid or engine initialization failed")
                }
            } else {
                print("⚠️ XR system already initialized")
            }
        })
    }
        .immersionStyle(selection: $immersionStyle, in: .mixed)
    }
}

struct ContentView: View {
    @Environment(\.openImmersiveSpace) private var openImmersiveSpace
    @Environment(\.openWindow) private var openWindow

    var body: some View {
        VStack(spacing: 30) {
            Text("BedroomTwin")
                .font(.extraLargeTitle)
                .fontWeight(.bold)

            Text("Powered by Untold Engine")
                .font(.title)
                .foregroundColor(.secondary)

        Button(action: {
            Task {
                await openImmersiveSpace(id: "ImmersiveSpace")
                openWindow(id: "TwinInfoPanel")
            }
        }) {
                Label("Start Experience", systemImage: "visionpro.fill")
                    .frame(minWidth: 250)
            }
            .buttonStyle(.borderedProminent)
            .controlSize(.large)

            Button(action: {
                openWindow(id: "EngineStatsPanel")
            }) {
                Label("Engine Stats", systemImage: "chart.xyaxis.line")
                    .frame(minWidth: 250)
            }
            .buttonStyle(.bordered)
            .controlSize(.large)
        }
        .padding(60)
    }
}

struct TwinInfoWindowView: View {
    @ObservedObject var store: TwinInfoWindowStore

    var body: some View {
        Group {
            if let info = store.selected {
                VStack(alignment: .leading, spacing: 14) {
                    Text(info.title)
                        .font(.title2)
                        .fontWeight(.bold)

                    HStack(spacing: 8) {
                        Circle()
                            .fill(statusColor(info.status))
                            .frame(width: 10, height: 10)
                        Text(info.status)
                            .font(.headline)
                    }

                    Text(info.detail)
                        .font(.body)
                        .foregroundColor(.secondary)

                    Spacer()

                    Text("Updated \(store.lastUpdated.formatted(date: .omitted, time: .standard))")
                        .font(.caption2)
                        .foregroundStyle(.tertiary)
                }
                .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .topLeading)
            } else {
                VStack(spacing: 10) {
                    Image(systemName: "hand.tap")
                        .font(.largeTitle)
                        .foregroundColor(.secondary)
                    Text("Tap an object in the room to see its live status")
                        .font(.subheadline)
                        .foregroundColor(.secondary)
                        .multilineTextAlignment(.center)
                }
                .frame(maxWidth: .infinity, maxHeight: .infinity)
            }
        }
        .padding(20)
    }

    private func statusColor(_ status: String) -> Color {
        switch status.lowercased() {
        case "on", "online", "open", "enabled":
            return .green
        case "off", "offline", "closed":
            return .red
        default:
            return .yellow
        }
    }
}

struct EngineStatsWindowView: View {
    @ObservedObject var store: EngineStatsWindowStore

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack {
                Text("Engine Stats")
                    .font(.headline)
                Spacer()
                Toggle("Advanced", isOn: $store.advancedMode)
                    .toggleStyle(.switch)
                    .controlSize(.small)
            }

            ScrollView {
                Text(store.advancedMode ? store.expandedText : store.compactText)
                    .font(.system(size: 12, design: .monospaced))
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .textSelection(.enabled)
            }
        }
        .padding(16)
    }
}