//
//  GameScene.swift
//  BedroomTwin
//
//  Generated by UntoldEngine Build System
//  visionOS Version
//

import Foundation
import simd
import UntoldEngine

extension SceneChannel {
    static let windowGeometry = SceneChannel.userCustom(index: 0)
}

struct TwinObjectInfo {
    let title: String
    let status: String
    let detail: String
}

let twinInfoByName: [String: TwinObjectInfo] = [
    "NM_Table_Lamp": TwinObjectInfo(
        title: "Table Lamp",
        status: "On",
        detail: "Brightness: 80%"
    ),
    "NM_CeilingLamp_Left": TwinObjectInfo(
        title: "Ceiling Lamp (Left)",
        status: "On",
        detail: "Brightness: 60%"
    ),
    "NM_CeilingLamp_Right": TwinObjectInfo(
        title: "Ceiling Lamp (Right)",
        status: "Off",
        detail: "Brightness: 0%"
    ),
    "NM_Door": TwinObjectInfo(
        title: "Bedroom Door",
        status: "Closed",
        detail: "Lock: Engaged"
    ),
    "NM_Curtains": TwinObjectInfo(
        title: "Curtains",
        status: "Online",
        detail: "Position: 30% | Automation: Enabled"
    ),
    "NM_Laptop": TwinObjectInfo(
        title: "Laptop",
        status: "Sleep",
        detail: "Battery: 62%"
    )
]

/// Multi-material objects export as one entity per material (suffixed `_mat0`, `_mat1`, ...)
/// with no parent wrapper entity. Strip that suffix so picking any submesh still resolves
/// to the object's twin info.
func twinLookupName(for entityId: EntityID) -> String {
    var name = getEntityName(entityId: entityId)
    if let range = name.range(of: #"_mat\d+$"#, options: .regularExpression) {
        name.removeSubrange(range)
    }
    return name
}

enum BedroomViewMode {
    case normal
    case wireframeShell
    case hiddenShell
    case passthroughWindow
}

func applyViewMode(_ mode: BedroomViewMode) {
    switch mode {
    case .normal:
        setSceneChannel(.contextGeometry, .renderMode(.normal))
        setSceneChannel(.windowGeometry, .renderMode(.normal))

    case .wireframeShell:
        setSceneChannel(.contextGeometry, .renderMode(.wireframe))
        setSceneChannel(.windowGeometry, .renderMode(.normal))

    case .hiddenShell:
        setSceneChannel(.contextGeometry, .renderMode(.hidden))
        setSceneChannel(.windowGeometry, .renderMode(.normal))

    case .passthroughWindow:
        setSceneChannel(.contextGeometry, .renderMode(.normal))
        setSceneChannel(.windowGeometry, .renderMode(.passthroughGhost(opacity: 0.0)))
    }
}

// GameScene: Initialize your game and write game-specific logic
class GameScene {
    
    private var selectedTwinObject: TwinObjectInfo?

    private let viewModes: [BedroomViewMode] = [.normal, .wireframeShell, .hiddenShell, .passthroughWindow]
    private var viewModeIndex = 0

    init() {
        Logger.log(message: "🎮 GameScene initializing...")

        // Configure asset paths with debug logging
        logBundleInfo()
        setupAssetPaths()

        // Configure game Systems
        configureEngineSystems()

        // Load your scene here
        
        registerSceneChannelPrefix("WIN_", channels: .windowGeometry)

        setSceneChannel(.contextGeometry, .pickParticipation(false))

        setSceneChannel(
            .windowGeometry,
            .lightPortal(.enabled(
                intensity: 0.5,
                range: 4.0,
                useRealWorldTint: true,
                maxActivePortals: 4,
                activationDistance: 10.0
            ))
        )

        applyViewMode(.normal)

        let room = createEntity()
        setEntityName(entityId: room, name: "DigitalTwin")

        setEntityMeshAsync(entityId: room, filename: "DigitalTwin", withExtension: "untold") { success in
            guard success else {
                setSceneReady(false)
                return
            }

            loadSceneAuthored(filename: "DigitalTwin", withExtension: "untold")
            setSceneReady(true)
        }



    }

    // MARK: - Setup Methods

    /// Configure game Systems for play mode
    private func configureEngineSystems() {
        gameMode = true

        registerXREvents()
        setInput(.xr(.pickingBackend(.octreeGPUPreferred)))
        setInput(.xr(.twoHandRotateAxisMode(.dynamicSnapped)))
        setInput(.xr(.sceneReady(true)))

        setRendering(.postProcessing(.enabled))
        setRendering(.antiAliasing(.msaa))
        setPostFX(.ssao(.enabled(false)))

        setRendering(.environment(.lightingMode(.realWorldEstimate)))
        setRendering(.environment(.realWorldLightingContribution(1.0)))

        TextureStreamingSystem.shared.apply(.superdetailed)
    }

    // MARK: - Game Loop

    /// Called every frame - add custom game logic here
    func update(deltaTime _: Float) {
        // Skip logic if not in game mode
        if gameMode == false { return }

        // Add your custom update logic here
    }

    /// Called for input handling - add custom input logic here
    func handleInput() {
        guard gameMode, isSceneReady() else { return }

        var state = getXRSpatialInputState()

        if state.spatialTapActive, let picked = state.pickedEntityId {
            selectedTwinObject = twinInfoByName[twinLookupName(for: picked)]

            if let info = selectedTwinObject {
                Logger.log(message: "\(info.title): \(info.status) - \(info.detail)")
                Task { @MainActor in
                    TwinInfoWindowStore.shared.selected = info
                    TwinInfoWindowStore.shared.lastUpdated = Date()
                }
            }
        } else if state.spatialTapActive {
            // Tapped empty space (nothing pickable under the ray) — cycle view modes for the demo.
            viewModeIndex = (viewModeIndex + 1) % viewModes.count
            let mode = viewModes[viewModeIndex]
            applyViewMode(mode)
            Logger.log(message: "View mode: \(mode)")
        }

        SpatialManipulationSystem.shared.processAnchoredSceneManipulationLifecycle(
            from: state,
            dragSensitivity: 10.0,
            rotateSensitivity: 1.0
        )

        // Add your custom input handling here
    }

}

@MainActor
final class TwinInfoWindowStore: ObservableObject {
    static let shared = TwinInfoWindowStore()

    @Published var selected: TwinObjectInfo?
    @Published var lastUpdated: Date = Date()

    private init() {}
}

@MainActor
final class EngineStatsWindowStore: ObservableObject {
    static let shared = EngineStatsWindowStore()

    @Published var advancedMode: Bool = false
    @Published private(set) var compactText: String = ""
    @Published private(set) var expandedText: String = ""

    private var timer: Timer?

    private init() {
        refresh()
        timer = Timer.scheduledTimer(withTimeInterval: 0.25, repeats: true) { [weak self] _ in
            guard let self else { return }
            Task { @MainActor in
                self.refresh()
            }
        }
    }

    deinit {
        timer?.invalidate()
    }

    private func refresh() {
        let snapshot = getEngineStatsSnapshot()
        compactText = formatEngineStatsCompact(snapshot)
        expandedText = formatEngineStatsOverlay(snapshot)
    }
}
