//
//  GameScene.swift
//  ArchvizViewer
//
//  Generated by UntoldEngine Build System
//  visionOS Version
//

import Foundation
import simd
import UntoldEngine

// GameScene: Initialize your game and write game-specific logic
class GameScene {

    init() {
        Logger.log(message: "🎮 GameScene initializing...")

        // Configure asset paths with debug logging
        logBundleInfo()
        setupAssetPaths()

        // Configure game Systems
        configureEngineSystems()

        // Load your scene here
        
        let entity = createEntity()
        setEntityName(entityId: entity, name: "Bedroom")

        setEntityMeshAsync(entityId: entity, filename: "Bedroom", withExtension: "untold") { success in
            guard success else {
                setSceneReady(false)
                return
            }

            loadSceneAuthored(filename: "Bedroom", withExtension: "untold")

            setRendering(.environment(.ibl(true)))
            setRendering(.environment(.asset("forest.exr")))
            setRendering(.environment(.intensity(0.9)))
            setRendering(.environment(.visible(true)))

            setSceneReady(true)
        }



    }

    // MARK: - Setup Methods

    /// Configure game Systems for play mode
    private func configureEngineSystems() {
        gameMode = true
        AnimationSystem.shared.isEnabled = true
        InputSystem.shared.registerXREvents()
        InputSystem.shared.setXRSpatialPickingBackendPreference(.octreeGPUPreferred)
        InputSystem.shared.setXRTwoHandRotateAxisMode(.dynamicSnapped)
        
        setInput(.xr(.sceneReady(true)))

        setRendering(.postProcessing(.enabled))
        setRendering(.antiAliasing(.msaa))
        setPostFX(.ssao(.enabled(false)))

        TextureStreamingSystem.shared.apply(.superdetailed)
    }

    // MARK: - Game Loop

    /// Called every frame - add custom game logic here
    func update(deltaTime _: Float) {
        // Skip logic if not in game mode
        if gameMode == false { return }

        // Add your custom update logic here
    }

    /// Called for input handling - add custom input logic here
    func handleInput() {
        // Skip logic if not in game mode
        if gameMode == false { return }
        if isSceneReady() == false {return}

        if gameMode == false { return }
        if isSceneReady() == false { return }

        let state = getXRSpatialInputState()

        SpatialManipulationSystem.shared.processAnchoredSceneManipulationLifecycle(
            from: state,
            dragSensitivity: 10.0,
            rotateSensitivity: 1.0
        )
    }

}

@MainActor
final class EngineStatsWindowStore: ObservableObject {
    static let shared = EngineStatsWindowStore()

    @Published var advancedMode: Bool = false
    @Published private(set) var compactText: String = ""
    @Published private(set) var expandedText: String = ""

    private var timer: Timer?

    private init() {
        refresh()
        timer = Timer.scheduledTimer(withTimeInterval: 0.25, repeats: true) { [weak self] _ in
            guard let self else { return }
            Task { @MainActor in
                self.refresh()
            }
        }
    }

    deinit {
        timer?.invalidate()
    }

    private func refresh() {
        let snapshot = getEngineStatsSnapshot()
        compactText = formatEngineStatsCompact(snapshot)
        expandedText = formatEngineStatsOverlay(snapshot)
    }
}
