//
//  GameSceneUtils.swift
//  ArchvizViewer
//
//  Generated by UntoldEngine Build System
//  visionOS Version
//

import Foundation
import UntoldEngine

extension GameScene {

    // MARK: - Asset Setup

    /// Log bundle information for debugging
    func logBundleInfo() {
        Logger.log(message: "📦 Bundle path: \(Bundle.main.bundlePath)")
        if let resourceURL = Bundle.main.resourceURL {
            Logger.log(message: "📦 Resource URL: \(resourceURL.path)")
            if let contents = try? FileManager.default.contentsOfDirectory(atPath: resourceURL.path) {
                Logger.log(message: "📦 Resources directory contents: \(contents.joined(separator: ", "))")
            }
        }
    }

    /// Configure the asset base path for the bundled GameData
    func setupAssetPaths() {
        if let gameDataURL = Bundle.main.url(forResource: "GameData", withExtension: nil) {
            assetBasePath = gameDataURL
            Logger.log(message: "✅ Found GameData at: \(gameDataURL.path)")
            if let contents = try? FileManager.default.contentsOfDirectory(atPath: gameDataURL.path) {
                Logger.log(message: "📦 GameData contents: \(contents.joined(separator: ", "))")
            }
        } else if let resourceURL = Bundle.main.resourceURL {
            let gameDataPath = resourceURL.appendingPathComponent("GameData")
            if FileManager.default.fileExists(atPath: gameDataPath.path) {
                assetBasePath = gameDataPath
                Logger.log(message: "✅ Found GameData in Resources: \(gameDataPath.path)")
                if let contents = try? FileManager.default.contentsOfDirectory(atPath: gameDataPath.path) {
                    Logger.log(message: "📦 GameData contents: \(contents.joined(separator: ", "))")
                }
            } else {
                Logger.log(message: "⚠️ GameData not found. Bundle resources: \(resourceURL.path)")
                Logger.log(message: "⚠️ Listing all files in bundle resources...")
                listDirectoryRecursively(at: resourceURL)
            }
        } else {
            Logger.log(message: "❌ Bundle.main.resourceURL is nil!")
        }
    }

    /// Recursively list directory contents for debugging
    func listDirectoryRecursively(at url: URL, depth: Int = 0) {
        let indent = String(repeating: "  ", count: depth)
        guard let contents = try? FileManager.default.contentsOfDirectory(atPath: url.path) else {
            return
        }
        for item in contents {
            let itemURL = url.appendingPathComponent(item)
            var isDirectory: ObjCBool = false
            if FileManager.default.fileExists(atPath: itemURL.path, isDirectory: &isDirectory) {
                Logger.log(message: "\(indent)📁 \(item)\(isDirectory.boolValue ? "/" : "")")
                if isDirectory.boolValue && depth < 2 {
                    listDirectoryRecursively(at: itemURL, depth: depth + 1)
                }
            }
        }
    }

}