//
//  GameScene.swift
//  ProceduralGeometry
//
//  Generated by UntoldEngine Build System
//  visionOS Version
//

import Foundation
import simd
import UntoldEngine
import ProceduralGeometryExtension

// GameScene: Initialize your game and write game-specific logic
class GameScene {

    /// The complete mutually-exclusive interaction mode for this demo.
    var pipeInteractionState: PipeInteractionState = .idle

    /// Maps each tube's two (otherwise invisible) endpoint proxy entities to the tube they
    /// belong to and whether each is the start or end. Exactly two entries per tube, for its
    /// whole lifetime — populated once per tube via `createTubeEndpointHandles`, called when a
    /// placed pipe is confirmed and selected (see `GameScene+PipePlacement.swift`). Unlike the old
    /// per-control-point handle scheme, nothing here ever needs reindexing: inserted bends are
    /// pure data in `TubePathComponent.controlPoints`, with no entity of their own.
    var tubeEndpointHandles: [EntityID: (tubeId: EntityID, isStart: Bool)] = [:]

    /// The reverse of `tubeEndpointHandles`: each tube's own two proxy entities, for toggling
    /// their visibility when a tube becomes (in)active.
    var tubeEndpoints: [EntityID: (startHandleId: EntityID, endHandleId: EntityID)] = [:]

    /// Maps each interior-bend proxy entity to the tube it belongs to and its control-point
    /// index. Unlike `tubeEndpointHandles`, these only exist while their tube is active, and are
    /// always wholesale-regenerated (never incrementally reindexed) whenever a drag concludes —
    /// see `regenerateInteriorBendProxies`.
    var tubeInteriorBendHandles: [EntityID: (tubeId: EntityID, index: Int)] = [:]

    /// Each active tube's current set of interior-bend proxy entities, for destroying them
    /// wholesale before regenerating (or when the tube deactivates).
    var tubeInteriorProxies: [EntityID: [EntityID]] = [:]

    /// Which tube, if any, is currently Selected or Editing — set by tapping the tube's own mesh
    /// (or one of its proxies), cleared by a two-hand pinch (see `checkTwoHandDeselect`). Selected
    /// vs. Editing is tracked separately by `isEditingActiveTube`; see
    /// `GameScene+TubeEditing.swift` for the full state machine (Idle / Selected / Editing).
    /// Last frame's combined both-hands-pinching state, so `checkTwoHandDeselect` can fire once
    /// on the rising edge rather than re-deselecting every frame both hands stay pinched.
    var wasTwoHandPinching = false

    /// The drag currently in progress, if any, paired with the proxy entity driving it — neither
    /// `TubeEndpointDrag`, `TubeInteriorBendDrag`, nor `TubeTranslationDrag` (from
    /// `ProceduralGeometryExtension`) has any idea proxy entities exist, so this demo tracks that
    /// pairing itself. See `GameScene+TubeEditing.swift`.
    ///
    /// Captured once when a gesture starts (the first frame `pickedEntityId` identifies one of
    /// the active tube's proxies, or — while merely Selected — the active tube's own body) and
    /// held until that gesture ends — `pickedEntityId` isn't guaranteed to keep pointing at the
    /// same entity, or to stay non-nil, all the way through to the gesture's final
    /// `.ended`/`.cancelled` frame, and `SpatialManipulationSystem`'s own session only gets
    /// cleanly closed out if its lifecycle function is called on that final frame too — skipping
    /// it leaves the session stuck mid-drag, still targeting whatever it was last acting on.
    /// How many pipes have been placed total, used to cycle `pipeColors` — every placed pipe gets
    /// a base identifying color, so `refreshTubeHighlight` always has one to brighten for
    /// Selected/Editing.
    var placedPipeCount = 0
    /// Each tube's own identifying color, as assigned at creation — the value `refreshTubeHighlight`
    /// brightens toward white for Selected/Editing, and restores exactly when a tube goes back to
    /// Idle. Keyed here (rather than re-read from the material) so repeated select/deselect cycles
    /// can't drift the color via accumulated blend rounding.
    var tubeBaseColors: [EntityID: SIMD3<Float>] = [:]

    init() {
        Logger.log(message: "🎮 GameScene initializing...")

        // Configure asset paths with debug logging
        logBundleInfo()
        setupAssetPaths()

        // Configure game Systems
        configureEngineSystems()

        // Load your scene here
        ProceduralGeometryExtension.shared.install()

        let light = createEntity()
        setEntityName(entityId: light, name: "Directional Light")
        createDirLight(entityId: light)

        setSceneReady(true)
    }

    // MARK: - Setup Methods

    /// Configure game Systems for play mode
    private func configureEngineSystems() {
        gameMode = true
        AnimationSystem.shared.isEnabled = true
        InputSystem.shared.registerXREvents()
        InputSystem.shared.setXRSpatialPickingBackendPreference(.octreeGPUPreferred)
        InputSystem.shared.setXRTwoHandRotateAxisMode(.dynamicSnapped)
    }

    // MARK: - Game Loop

    /// Called every frame - add custom game logic here
    func update(deltaTime _: Float) {
        // Skip logic if not in game mode
        if gameMode == false { return }

        // Add your custom update logic here
    }

    /// Called for input handling - add custom input logic here
    func handleInput() {
        // Skip logic if not in game mode
        if gameMode == false { return }
        if isSceneReady() == false {return}

        let state = InputSystem.shared.xrSpatialInputState

        // Live-track the "place a new pipe" preview against whatever wall/floor the user is
        // currently looking at — independent of tap handling below, so it's already in position
        // by the time a tap arrives. See GameScene+PipePlacement.swift.
        updatePipePlacementPreview(state: state)

        // Two-hand deselection has priority, so the same snapshot can never select/edit and then
        // immediately deselect a pipe.
        let didDeselect = checkTwoHandDeselect(state: state)

        // A tap (single pinch, not a drag) selects a tube; a later tap on the selected tube
        // enters Editing. A tap on empty space does
        // nothing now — see checkTwoHandDeselect below for why deselection moved to its own,
        // distinct gesture. This is checked independently of the drag state below — a tap is a
        // distinct, already-resolved gesture (see SpatialInputTutorial.md), never concurrent with
        // an active drag.
        //
        // Placement taps (confirming the preview) are checked first: the preview is a real
        // TubePathComponent entity, so handleTubeTap's generic "tap a tube to select it" dispatch
        // would otherwise catch a tap meant to confirm it instead.
        if state.spatialTapActive, !didDeselect {
            if !handlePipePlacementTap(pickedEntityId: state.pickedEntityId) {
                handleTubeTap(pickedEntityId: state.pickedEntityId)
            }
        }

        // Both hands pinching at once (edge-triggered) deselects whichever tube is active,
        // regardless of what's under the gaze at that instant — a deliberately distinct gesture
        // from the single-hand tap used to select/confirm placement, so there's no single input
        // signal for "deselect" and "confirm/create a pipe" to ever race on. This was the actual
        // cause of an earlier bug (deselecting via an empty-space tap could, on some frames of
        // that same gesture, also read as confirming a placement preview that had just become
        // eligible to exist) — splitting them onto genuinely different gestures removes the
        // possibility structurally, rather than patching the timing.
        // Latch onto a proxy (Editing) or the active tube's own body (Selected, for a whole-tube
        // move) only at the start of a gesture — once a drag is under way, keep driving the same
        // target regardless of what pickedEntityId reports frame to frame. `beginTubeDrag` itself
        // refuses to start unless it's actually this tube system's to drag, so a stray pinch over
        // an unarmed tube falls through to the scene-manipulation branch below instead of doing
        // anything tube-specific.
        //
        // Deliberately NOT gated on state.spatialTapActive: that flag means "this gesture
        // turned out to be a tap, not a drag" and is false for the entire duration of an
        // actual drag (see SpatialInputTutorial.md) — gating on it here meant a real drag
        // could never latch onto a proxy at all, so every attempt fell through to the
        // scene-root-drag branch below instead.
        if !didDeselect,
           state.spatialDragActive,
           case .changed = state.currentPhase,
           !pipeInteractionState.isDragging,
           let entityId = state.pickedEntityId {
            beginTubeDrag(pickedEntityId: entityId, dragOrigin: state.inputDevicePositionWorld)
        }

        // Mutually exclusive: dragging a proxy (or the whole tube) must not also drag the scene
        // root under the same gesture, or everything in view appears to move together.
        if case let .dragging(currentValue, returnMode, finishedValue) = pipeInteractionState {
            var current = currentValue
            var isFinished = finishedValue
            // Call every frame for as long as our gesture is live — including its last frame — so
            // SpatialManipulationSystem's own begin/update/end lifecycle actually reaches `end`
            // instead of getting stuck mid-drag on this entity. Not called at all for a whole-tube
            // move: that drag kind has no proxy entity of its own for SpatialManipulationSystem to
            // move (it tracks the raw pinch position directly instead, see updateActiveDrag) —
            // calling this with pickedEntityId == the tube itself would move the tube's own
            // transform on top of the control-point shift already being applied, double-counting
            // the same motion.
            switch current {
            case .endpoint, .interiorBend:
                SpatialManipulationSystem.shared.processPinchTransformLifecycle(from: state)
            case .wholeTube:
                break
            }

            let isGestureEnding = state.currentPhase == .ended || state.currentPhase == .cancelled
            // ...then feed the current position into whichever drag type is active (the
            // axis-locked/90-degree-only editing logic itself lives in
            // ProceduralGeometryExtension now) and move the proxy to wherever that reports back.
            // On the gesture's final frame this calls .end instead of .update — pinch release is
            // commonly accompanied by a small involuntary hand movement, which .update's
            // turn/collapse detection would otherwise be free to read as deliberate and insert
            // (or remove) a bend right at the moment of release.
            if !isFinished {
                let stillGoing = updateActiveDrag(
                    &current,
                    isGestureEnding: isGestureEnding,
                    rawDevicePosition: state.inputDevicePositionWorld
                )
                if !stillGoing {
                    isFinished = true
                }
            }
            pipeInteractionState = .dragging(current, returnMode: returnMode, finished: isFinished)
            // An interior-bend drag can rigidly shift an endpoint's position within the tube
            // without ever touching that endpoint's own proxy entity — keep them in sync every
            // frame so the two never visibly drift apart mid-drag.
            syncEndpointProxies(tubeId: current.tubeId)

            if isGestureEnding {
                switch returnMode {
                case .selected:
                    transitionPipeInteraction(to: .selected(current.tubeId))
                case .editing:
                    transitionPipeInteraction(to: .editing(current.tubeId))
                    regenerateInteriorBendProxies(tubeId: current.tubeId)
                }
            }
        } else if pipeInteractionState.hasFocusedTube == false {
            // Nothing armed for editing and nothing of ours was picked — Pinch + Drag moves the
            // scene root, two-hands rotate rotates it.
            //
            // Gated on activeTubeId, not just "no active drag": without this, a pinch that
            // merely missed a proxy's small hit target (rather than landing on empty space)
            // would fall straight through to dragging the *entire scene* — surprising and
            // disruptive mid-edit, since arming a tube is already a deliberate signal of intent
            // to edit it. To look around again, tap away to disarm first.
//            SpatialManipulationSystem.shared.processAnchoredSceneManipulationLifecycle(
//                from: state,
//                dragSensitivity: 10.0,
//                rotateSensitivity: 1.0
//            )
        }

        // Add your custom input handling here
    }

}

@MainActor
final class EngineStatsWindowStore: ObservableObject {
    static let shared = EngineStatsWindowStore()

    @Published var advancedMode: Bool = false
    @Published private(set) var compactText: String = ""
    @Published private(set) var expandedText: String = ""

    private var timer: Timer?

    private init() {
        refresh()
        timer = Timer.scheduledTimer(withTimeInterval: 0.25, repeats: true) { [weak self] _ in
            guard let self else { return }
            Task { @MainActor in
                self.refresh()
            }
        }
    }

    deinit {
        timer?.invalidate()
    }

    private func refresh() {
        let snapshot = getEngineStatsSnapshot()
        compactText = formatEngineStatsCompact(snapshot)
        expandedText = formatEngineStatsOverlay(snapshot)
    }
}
